/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../common";

export type BridgeDataStruct = {
  bridge: PromiseOrValue<string>;
  from: PromiseOrValue<string>;
  to: PromiseOrValue<string>;
  receiver: PromiseOrValue<string>;
  minAmount: PromiseOrValue<BigNumberish>;
  destinationChainId: PromiseOrValue<BigNumberish>;
  hasSourceSwaps: PromiseOrValue<boolean>;
  hasDestinationCall: PromiseOrValue<boolean>;
};

export type BridgeDataStructOutput = [
  string,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  boolean,
  boolean
] & {
  bridge: string;
  from: string;
  to: string;
  receiver: string;
  minAmount: BigNumber;
  destinationChainId: BigNumber;
  hasSourceSwaps: boolean;
  hasDestinationCall: boolean;
};

export type SwapInfoStruct = {
  dex: PromiseOrValue<string>;
  fromToken: PromiseOrValue<string>;
  toToken: PromiseOrValue<string>;
  fromAmount: PromiseOrValue<BigNumberish>;
  leftOverFromAmount: PromiseOrValue<BigNumberish>;
  returnToAmount: PromiseOrValue<BigNumberish>;
};

export type SwapInfoStructOutput = [
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  dex: string;
  fromToken: string;
  toToken: string;
  fromAmount: BigNumber;
  leftOverFromAmount: BigNumber;
  returnToAmount: BigNumber;
};

export type CallToFunctionInfoStruct = {
  isAvailable: PromiseOrValue<boolean>;
  offset: PromiseOrValue<BigNumberish>;
};

export type CallToFunctionInfoStructOutput = [boolean, BigNumber] & {
  isAvailable: boolean;
  offset: BigNumber;
};

export type FeeInfoStruct = {
  tokenFee: PromiseOrValue<BigNumberish>;
  fixedNativeFeeAmount: PromiseOrValue<BigNumberish>;
  dzapTokenShare: PromiseOrValue<BigNumberish>;
  dzapFixedNativeShare: PromiseOrValue<BigNumberish>;
};

export type FeeInfoStructOutput = [
  BigNumber,
  BigNumber,
  BigNumber,
  BigNumber
] & {
  tokenFee: BigNumber;
  fixedNativeFeeAmount: BigNumber;
  dzapTokenShare: BigNumber;
  dzapFixedNativeShare: BigNumber;
};

export type CrossChainDataStruct = {
  callTo: PromiseOrValue<string>;
  approveTo: PromiseOrValue<string>;
  extraNative: PromiseOrValue<BigNumberish>;
  permit: PromiseOrValue<BytesLike>;
  callData: PromiseOrValue<BytesLike>;
};

export type CrossChainDataStructOutput = [
  string,
  string,
  BigNumber,
  string,
  string
] & {
  callTo: string;
  approveTo: string;
  extraNative: BigNumber;
  permit: string;
  callData: string;
};

export type SwapDataStruct = {
  callTo: PromiseOrValue<string>;
  approveTo: PromiseOrValue<string>;
  from: PromiseOrValue<string>;
  to: PromiseOrValue<string>;
  fromAmount: PromiseOrValue<BigNumberish>;
  minToAmount: PromiseOrValue<BigNumberish>;
  swapCallData: PromiseOrValue<BytesLike>;
  permit: PromiseOrValue<BytesLike>;
};

export type SwapDataStructOutput = [
  string,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  string,
  string
] & {
  callTo: string;
  approveTo: string;
  from: string;
  to: string;
  fromAmount: BigNumber;
  minToAmount: BigNumber;
  swapCallData: string;
  permit: string;
};

export interface IDZapDiamondInterface extends utils.Interface {
  functions: {
    "addDex(address)": FunctionFragment;
    "addressCanExecuteMethod(bytes4,address)": FunctionFragment;
    "batchAddDex(address[])": FunctionFragment;
    "batchRemoveDex(address[])": FunctionFragment;
    "batchSetFunctionApprovalBySignature(address[],bytes4[],bool[])": FunctionFragment;
    "bridge(bytes32,address,address,(string,address,address,address,uint256,uint256,bool,bool),(address,address,uint256,bytes,bytes))": FunctionFragment;
    "bridgeMultipleTokens(bytes32,address,address,(string,address,address,address,uint256,uint256,bool,bool)[],(address,address,uint256,bytes,bytes)[])": FunctionFragment;
    "calcFixedNativeFees(address,uint8)": FunctionFragment;
    "calcTokenFees(address,uint8,uint256)": FunctionFragment;
    "getSelectorInfo(address,bytes4)": FunctionFragment;
    "integratorFeeInfo(address,uint8)": FunctionFragment;
    "isContractApproved(address)": FunctionFragment;
    "isFunctionApproved(address,bytes4)": FunctionFragment;
    "isIntegratorAllowed(address)": FunctionFragment;
    "maxFixedNativeFeeAmount()": FunctionFragment;
    "maxTokenFee()": FunctionFragment;
    "multiSwap(bytes32,address,address,address,(address,address,address,address,uint256,uint256,bytes,bytes)[])": FunctionFragment;
    "multiSwapWithoutRevert(bytes32,address,address,address,(address,address,address,address,uint256,uint256,bytes,bytes)[])": FunctionFragment;
    "owner()": FunctionFragment;
    "protocolFeeVault()": FunctionFragment;
    "removeDex(address)": FunctionFragment;
    "removeIntegrator(address)": FunctionFragment;
    "setBatchCanExecute(bytes4[],address[],bool[])": FunctionFragment;
    "setCanExecute(bytes4,address,bool)": FunctionFragment;
    "setFunctionApprovalBySignature(address,bytes4,bool)": FunctionFragment;
    "setIntegratorInfo(address,uint8[],(uint256,uint256,uint256,uint256)[])": FunctionFragment;
    "setProtocolFeeVault(address)": FunctionFragment;
    "swap(bytes32,address,address,address,(address,address,address,address,uint256,uint256,bytes,bytes))": FunctionFragment;
    "swapAndBridge(bytes32,address,address,(string,address,address,address,uint256,uint256,bool,bool)[],(address,address,address,address,uint256,uint256,bytes,bytes)[],(address,address,uint256,bytes,bytes)[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "updateSelectorInfo(address[],bytes4[],(bool,uint256)[])": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "addDex"
      | "addressCanExecuteMethod"
      | "batchAddDex"
      | "batchRemoveDex"
      | "batchSetFunctionApprovalBySignature"
      | "bridge"
      | "bridgeMultipleTokens"
      | "calcFixedNativeFees"
      | "calcTokenFees"
      | "getSelectorInfo"
      | "integratorFeeInfo"
      | "isContractApproved"
      | "isFunctionApproved"
      | "isIntegratorAllowed"
      | "maxFixedNativeFeeAmount"
      | "maxTokenFee"
      | "multiSwap"
      | "multiSwapWithoutRevert"
      | "owner"
      | "protocolFeeVault"
      | "removeDex"
      | "removeIntegrator"
      | "setBatchCanExecute"
      | "setCanExecute"
      | "setFunctionApprovalBySignature"
      | "setIntegratorInfo"
      | "setProtocolFeeVault"
      | "swap"
      | "swapAndBridge"
      | "transferOwnership"
      | "updateSelectorInfo"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addDex",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "addressCanExecuteMethod",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "batchAddDex",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRemoveDex",
    values: [PromiseOrValue<string>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetFunctionApprovalBySignature",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<boolean>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bridge",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      BridgeDataStruct,
      CrossChainDataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "bridgeMultipleTokens",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      BridgeDataStruct[],
      CrossChainDataStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "calcFixedNativeFees",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "calcTokenFees",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "getSelectorInfo",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "integratorFeeInfo",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "isContractApproved",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "isFunctionApproved",
    values: [PromiseOrValue<string>, PromiseOrValue<BytesLike>]
  ): string;
  encodeFunctionData(
    functionFragment: "isIntegratorAllowed",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "maxFixedNativeFeeAmount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxTokenFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "multiSwap",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      SwapDataStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "multiSwapWithoutRevert",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      SwapDataStruct[]
    ]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "protocolFeeVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeDex",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "removeIntegrator",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "setBatchCanExecute",
    values: [
      PromiseOrValue<BytesLike>[],
      PromiseOrValue<string>[],
      PromiseOrValue<boolean>[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setCanExecute",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setFunctionApprovalBySignature",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<boolean>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setIntegratorInfo",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>[],
      FeeInfoStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setProtocolFeeVault",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "swap",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      SwapDataStruct
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndBridge",
    values: [
      PromiseOrValue<BytesLike>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      BridgeDataStruct[],
      SwapDataStruct[],
      CrossChainDataStruct[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "updateSelectorInfo",
    values: [
      PromiseOrValue<string>[],
      PromiseOrValue<BytesLike>[],
      CallToFunctionInfoStruct[]
    ]
  ): string;

  decodeFunctionResult(functionFragment: "addDex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addressCanExecuteMethod",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchAddDex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRemoveDex",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchSetFunctionApprovalBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "bridge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "bridgeMultipleTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcFixedNativeFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "calcTokenFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSelectorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "integratorFeeInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isContractApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isFunctionApproved",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isIntegratorAllowed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxFixedNativeFeeAmount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxTokenFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "multiSwap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "multiSwapWithoutRevert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "protocolFeeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "removeDex", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeIntegrator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBatchCanExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCanExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setFunctionApprovalBySignature",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIntegratorInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setProtocolFeeVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "swap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapAndBridge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateSelectorInfo",
    data: BytesLike
  ): Result;

  events: {
    "BridgeTransferStarted(bytes32,address,address,address,tuple)": EventFragment;
    "DexAdded(address)": EventFragment;
    "DexRemoved(address)": EventFragment;
    "ExecutionAllowed(address,bytes4)": EventFragment;
    "ExecutionDenied(address,bytes4)": EventFragment;
    "FunctionSignatureApprovalChanged(address,bytes4,bool)": EventFragment;
    "MultiSwapped(bytes32,address,address,address,address,tuple[])": EventFragment;
    "MultiTokenBridgeTransferStarted(bytes32,address,address,address,tuple[])": EventFragment;
    "SelectorToInfoUpdated(address[],bytes4[],tuple[])": EventFragment;
    "SetDzapFixedNativeFeeAmount(uint256)": EventFragment;
    "SetDzapTokenFee(uint256)": EventFragment;
    "SetFixedNativeFee(uint256)": EventFragment;
    "SetIntegrator(address,uint8[],tuple[])": EventFragment;
    "SetMaxPlatformFee(uint256)": EventFragment;
    "SetPlatformFee(uint256)": EventFragment;
    "SwapBridgeTransferStarted(bytes32,address,address,address,tuple[],tuple[])": EventFragment;
    "Swapped(bytes32,address,address,address,address,tuple)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BridgeTransferStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DexAdded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "DexRemoved"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutionAllowed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "ExecutionDenied"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "FunctionSignatureApprovalChanged"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "MultiSwapped"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "MultiTokenBridgeTransferStarted"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SelectorToInfoUpdated"): EventFragment;
  getEvent(
    nameOrSignatureOrTopic: "SetDzapFixedNativeFeeAmount"
  ): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetDzapTokenFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetFixedNativeFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetIntegrator"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetMaxPlatformFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetPlatformFee"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SwapBridgeTransferStarted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Swapped"): EventFragment;
}

export interface BridgeTransferStartedEventObject {
  transactionId: string;
  integrator: string;
  sender: string;
  refundee: string;
  bridgeData: BridgeDataStructOutput;
}
export type BridgeTransferStartedEvent = TypedEvent<
  [string, string, string, string, BridgeDataStructOutput],
  BridgeTransferStartedEventObject
>;

export type BridgeTransferStartedEventFilter =
  TypedEventFilter<BridgeTransferStartedEvent>;

export interface DexAddedEventObject {
  dexAddress: string;
}
export type DexAddedEvent = TypedEvent<[string], DexAddedEventObject>;

export type DexAddedEventFilter = TypedEventFilter<DexAddedEvent>;

export interface DexRemovedEventObject {
  dexAddress: string;
}
export type DexRemovedEvent = TypedEvent<[string], DexRemovedEventObject>;

export type DexRemovedEventFilter = TypedEventFilter<DexRemovedEvent>;

export interface ExecutionAllowedEventObject {
  account: string;
  method: string;
}
export type ExecutionAllowedEvent = TypedEvent<
  [string, string],
  ExecutionAllowedEventObject
>;

export type ExecutionAllowedEventFilter =
  TypedEventFilter<ExecutionAllowedEvent>;

export interface ExecutionDeniedEventObject {
  account: string;
  method: string;
}
export type ExecutionDeniedEvent = TypedEvent<
  [string, string],
  ExecutionDeniedEventObject
>;

export type ExecutionDeniedEventFilter = TypedEventFilter<ExecutionDeniedEvent>;

export interface FunctionSignatureApprovalChangedEventObject {
  dex: string;
  functionSignature: string;
  approved: boolean;
}
export type FunctionSignatureApprovalChangedEvent = TypedEvent<
  [string, string, boolean],
  FunctionSignatureApprovalChangedEventObject
>;

export type FunctionSignatureApprovalChangedEventFilter =
  TypedEventFilter<FunctionSignatureApprovalChangedEvent>;

export interface MultiSwappedEventObject {
  transactionId: string;
  integrator: string;
  sender: string;
  refundee: string;
  recipient: string;
  swapInfo: SwapInfoStructOutput[];
}
export type MultiSwappedEvent = TypedEvent<
  [string, string, string, string, string, SwapInfoStructOutput[]],
  MultiSwappedEventObject
>;

export type MultiSwappedEventFilter = TypedEventFilter<MultiSwappedEvent>;

export interface MultiTokenBridgeTransferStartedEventObject {
  transactionId: string;
  integrator: string;
  sender: string;
  refundee: string;
  bridgeData: BridgeDataStructOutput[];
}
export type MultiTokenBridgeTransferStartedEvent = TypedEvent<
  [string, string, string, string, BridgeDataStructOutput[]],
  MultiTokenBridgeTransferStartedEventObject
>;

export type MultiTokenBridgeTransferStartedEventFilter =
  TypedEventFilter<MultiTokenBridgeTransferStartedEvent>;

export interface SelectorToInfoUpdatedEventObject {
  routers: string[];
  selectors: string[];
  info: CallToFunctionInfoStructOutput[];
}
export type SelectorToInfoUpdatedEvent = TypedEvent<
  [string[], string[], CallToFunctionInfoStructOutput[]],
  SelectorToInfoUpdatedEventObject
>;

export type SelectorToInfoUpdatedEventFilter =
  TypedEventFilter<SelectorToInfoUpdatedEvent>;

export interface SetDzapFixedNativeFeeAmountEventObject {
  fee: BigNumber;
}
export type SetDzapFixedNativeFeeAmountEvent = TypedEvent<
  [BigNumber],
  SetDzapFixedNativeFeeAmountEventObject
>;

export type SetDzapFixedNativeFeeAmountEventFilter =
  TypedEventFilter<SetDzapFixedNativeFeeAmountEvent>;

export interface SetDzapTokenFeeEventObject {
  fee: BigNumber;
}
export type SetDzapTokenFeeEvent = TypedEvent<
  [BigNumber],
  SetDzapTokenFeeEventObject
>;

export type SetDzapTokenFeeEventFilter = TypedEventFilter<SetDzapTokenFeeEvent>;

export interface SetFixedNativeFeeEventObject {
  fee: BigNumber;
}
export type SetFixedNativeFeeEvent = TypedEvent<
  [BigNumber],
  SetFixedNativeFeeEventObject
>;

export type SetFixedNativeFeeEventFilter =
  TypedEventFilter<SetFixedNativeFeeEvent>;

export interface SetIntegratorEventObject {
  integrator: string;
  feeType: number[];
  info: FeeInfoStructOutput[];
}
export type SetIntegratorEvent = TypedEvent<
  [string, number[], FeeInfoStructOutput[]],
  SetIntegratorEventObject
>;

export type SetIntegratorEventFilter = TypedEventFilter<SetIntegratorEvent>;

export interface SetMaxPlatformFeeEventObject {
  fee: BigNumber;
}
export type SetMaxPlatformFeeEvent = TypedEvent<
  [BigNumber],
  SetMaxPlatformFeeEventObject
>;

export type SetMaxPlatformFeeEventFilter =
  TypedEventFilter<SetMaxPlatformFeeEvent>;

export interface SetPlatformFeeEventObject {
  fee: BigNumber;
}
export type SetPlatformFeeEvent = TypedEvent<
  [BigNumber],
  SetPlatformFeeEventObject
>;

export type SetPlatformFeeEventFilter = TypedEventFilter<SetPlatformFeeEvent>;

export interface SwapBridgeTransferStartedEventObject {
  transactionId: string;
  integrator: string;
  sender: string;
  refundee: string;
  bridgeData: BridgeDataStructOutput[];
  swapInfo: SwapInfoStructOutput[];
}
export type SwapBridgeTransferStartedEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    BridgeDataStructOutput[],
    SwapInfoStructOutput[]
  ],
  SwapBridgeTransferStartedEventObject
>;

export type SwapBridgeTransferStartedEventFilter =
  TypedEventFilter<SwapBridgeTransferStartedEvent>;

export interface SwappedEventObject {
  transactionId: string;
  integrator: string;
  sender: string;
  refundee: string;
  recipient: string;
  swapInfo: SwapInfoStructOutput;
}
export type SwappedEvent = TypedEvent<
  [string, string, string, string, string, SwapInfoStructOutput],
  SwappedEventObject
>;

export type SwappedEventFilter = TypedEventFilter<SwappedEvent>;

export interface IDZapDiamond extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IDZapDiamondInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    addDex(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    addressCanExecuteMethod(
      _selector: PromiseOrValue<BytesLike>,
      _executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    batchAddDex(
      _dexs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchRemoveDex(
      _dexs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    batchSetFunctionApprovalBySignature(
      _dexs: PromiseOrValue<string>[],
      _signatures: PromiseOrValue<BytesLike>[],
      _approval: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bridge(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct,
      _genericData: CrossChainDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    bridgeMultipleTokens(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct[],
      _genericData: CrossChainDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    calcFixedNativeFees(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        fixedNativeFeeAmount: BigNumber;
        dzapShare: BigNumber;
      }
    >;

    calcTokenFees(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { totalFee: BigNumber; dzapShare: BigNumber }
    >;

    getSelectorInfo(
      _router: PromiseOrValue<string>,
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[CallToFunctionInfoStructOutput]>;

    integratorFeeInfo(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[FeeInfoStructOutput]>;

    isContractApproved(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isFunctionApproved(
      _dex: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    isIntegratorAllowed(
      _integrator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    maxFixedNativeFeeAmount(
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { _maxFixedNativeFee: BigNumber }>;

    maxTokenFee(overrides?: CallOverrides): Promise<[BigNumber]>;

    multiSwap(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    multiSwapWithoutRevert(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string] & { owner_: string }>;

    protocolFeeVault(overrides?: CallOverrides): Promise<[string]>;

    removeDex(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    removeIntegrator(
      _integrator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setBatchCanExecute(
      _selector: PromiseOrValue<BytesLike>[],
      _executor: PromiseOrValue<string>[],
      _canExecute: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setCanExecute(
      _selector: PromiseOrValue<BytesLike>,
      _executor: PromiseOrValue<string>,
      _canExecute: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setFunctionApprovalBySignature(
      _dex: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      _approval: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setIntegratorInfo(
      _integrator: PromiseOrValue<string>,
      _feeTypes: PromiseOrValue<BigNumberish>[],
      _feeInfo: FeeInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setProtocolFeeVault(
      _protocolFeeVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swap(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    swapAndBridge(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct[],
      _swapData: SwapDataStruct[],
      _genericData: CrossChainDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    updateSelectorInfo(
      _routers: PromiseOrValue<string>[],
      _selectors: PromiseOrValue<BytesLike>[],
      _infos: CallToFunctionInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  addDex(
    _dex: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  addressCanExecuteMethod(
    _selector: PromiseOrValue<BytesLike>,
    _executor: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  batchAddDex(
    _dexs: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchRemoveDex(
    _dexs: PromiseOrValue<string>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  batchSetFunctionApprovalBySignature(
    _dexs: PromiseOrValue<string>[],
    _signatures: PromiseOrValue<BytesLike>[],
    _approval: PromiseOrValue<boolean>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bridge(
    _transactionId: PromiseOrValue<BytesLike>,
    _integrator: PromiseOrValue<string>,
    _refundee: PromiseOrValue<string>,
    _bridgeData: BridgeDataStruct,
    _genericData: CrossChainDataStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  bridgeMultipleTokens(
    _transactionId: PromiseOrValue<BytesLike>,
    _integrator: PromiseOrValue<string>,
    _refundee: PromiseOrValue<string>,
    _bridgeData: BridgeDataStruct[],
    _genericData: CrossChainDataStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  calcFixedNativeFees(
    _integrator: PromiseOrValue<string>,
    _feeType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & {
      fixedNativeFeeAmount: BigNumber;
      dzapShare: BigNumber;
    }
  >;

  calcTokenFees(
    _integrator: PromiseOrValue<string>,
    _feeType: PromiseOrValue<BigNumberish>,
    _amount: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber] & { totalFee: BigNumber; dzapShare: BigNumber }
  >;

  getSelectorInfo(
    _router: PromiseOrValue<string>,
    _selector: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<CallToFunctionInfoStructOutput>;

  integratorFeeInfo(
    _integrator: PromiseOrValue<string>,
    _feeType: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<FeeInfoStructOutput>;

  isContractApproved(
    _dex: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isFunctionApproved(
    _dex: PromiseOrValue<string>,
    _signature: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  isIntegratorAllowed(
    _integrator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>;

  maxFixedNativeFeeAmount(overrides?: CallOverrides): Promise<BigNumber>;

  maxTokenFee(overrides?: CallOverrides): Promise<BigNumber>;

  multiSwap(
    _transactionId: PromiseOrValue<BytesLike>,
    _integrator: PromiseOrValue<string>,
    _refundee: PromiseOrValue<string>,
    _recipient: PromiseOrValue<string>,
    _data: SwapDataStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  multiSwapWithoutRevert(
    _transactionId: PromiseOrValue<BytesLike>,
    _integrator: PromiseOrValue<string>,
    _refundee: PromiseOrValue<string>,
    _recipient: PromiseOrValue<string>,
    _data: SwapDataStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  protocolFeeVault(overrides?: CallOverrides): Promise<string>;

  removeDex(
    _dex: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  removeIntegrator(
    _integrator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setBatchCanExecute(
    _selector: PromiseOrValue<BytesLike>[],
    _executor: PromiseOrValue<string>[],
    _canExecute: PromiseOrValue<boolean>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setCanExecute(
    _selector: PromiseOrValue<BytesLike>,
    _executor: PromiseOrValue<string>,
    _canExecute: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setFunctionApprovalBySignature(
    _dex: PromiseOrValue<string>,
    _signature: PromiseOrValue<BytesLike>,
    _approval: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setIntegratorInfo(
    _integrator: PromiseOrValue<string>,
    _feeTypes: PromiseOrValue<BigNumberish>[],
    _feeInfo: FeeInfoStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setProtocolFeeVault(
    _protocolFeeVault: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swap(
    _transactionId: PromiseOrValue<BytesLike>,
    _integrator: PromiseOrValue<string>,
    _refundee: PromiseOrValue<string>,
    _recipient: PromiseOrValue<string>,
    _data: SwapDataStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  swapAndBridge(
    _transactionId: PromiseOrValue<BytesLike>,
    _integrator: PromiseOrValue<string>,
    _refundee: PromiseOrValue<string>,
    _bridgeData: BridgeDataStruct[],
    _swapData: SwapDataStruct[],
    _genericData: CrossChainDataStruct[],
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    _newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  updateSelectorInfo(
    _routers: PromiseOrValue<string>[],
    _selectors: PromiseOrValue<BytesLike>[],
    _infos: CallToFunctionInfoStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    addDex(
      _dex: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    addressCanExecuteMethod(
      _selector: PromiseOrValue<BytesLike>,
      _executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    batchAddDex(
      _dexs: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchRemoveDex(
      _dexs: PromiseOrValue<string>[],
      overrides?: CallOverrides
    ): Promise<void>;

    batchSetFunctionApprovalBySignature(
      _dexs: PromiseOrValue<string>[],
      _signatures: PromiseOrValue<BytesLike>[],
      _approval: PromiseOrValue<boolean>[],
      overrides?: CallOverrides
    ): Promise<void>;

    bridge(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct,
      _genericData: CrossChainDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    bridgeMultipleTokens(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct[],
      _genericData: CrossChainDataStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    calcFixedNativeFees(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & {
        fixedNativeFeeAmount: BigNumber;
        dzapShare: BigNumber;
      }
    >;

    calcTokenFees(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber] & { totalFee: BigNumber; dzapShare: BigNumber }
    >;

    getSelectorInfo(
      _router: PromiseOrValue<string>,
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<CallToFunctionInfoStructOutput>;

    integratorFeeInfo(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<FeeInfoStructOutput>;

    isContractApproved(
      _dex: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isFunctionApproved(
      _dex: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isIntegratorAllowed(
      _integrator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>;

    maxFixedNativeFeeAmount(overrides?: CallOverrides): Promise<BigNumber>;

    maxTokenFee(overrides?: CallOverrides): Promise<BigNumber>;

    multiSwap(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    multiSwapWithoutRevert(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    protocolFeeVault(overrides?: CallOverrides): Promise<string>;

    removeDex(
      _dex: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    removeIntegrator(
      _integrator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    setBatchCanExecute(
      _selector: PromiseOrValue<BytesLike>[],
      _executor: PromiseOrValue<string>[],
      _canExecute: PromiseOrValue<boolean>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setCanExecute(
      _selector: PromiseOrValue<BytesLike>,
      _executor: PromiseOrValue<string>,
      _canExecute: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setFunctionApprovalBySignature(
      _dex: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      _approval: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setIntegratorInfo(
      _integrator: PromiseOrValue<string>,
      _feeTypes: PromiseOrValue<BigNumberish>[],
      _feeInfo: FeeInfoStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    setProtocolFeeVault(
      _protocolFeeVault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    swap(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    swapAndBridge(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct[],
      _swapData: SwapDataStruct[],
      _genericData: CrossChainDataStruct[],
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    updateSelectorInfo(
      _routers: PromiseOrValue<string>[],
      _selectors: PromiseOrValue<BytesLike>[],
      _infos: CallToFunctionInfoStruct[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BridgeTransferStarted(bytes32,address,address,address,tuple)"(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      bridgeData?: null
    ): BridgeTransferStartedEventFilter;
    BridgeTransferStarted(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      bridgeData?: null
    ): BridgeTransferStartedEventFilter;

    "DexAdded(address)"(
      dexAddress?: PromiseOrValue<string> | null
    ): DexAddedEventFilter;
    DexAdded(dexAddress?: PromiseOrValue<string> | null): DexAddedEventFilter;

    "DexRemoved(address)"(
      dexAddress?: PromiseOrValue<string> | null
    ): DexRemovedEventFilter;
    DexRemoved(
      dexAddress?: PromiseOrValue<string> | null
    ): DexRemovedEventFilter;

    "ExecutionAllowed(address,bytes4)"(
      account?: PromiseOrValue<string> | null,
      method?: PromiseOrValue<BytesLike> | null
    ): ExecutionAllowedEventFilter;
    ExecutionAllowed(
      account?: PromiseOrValue<string> | null,
      method?: PromiseOrValue<BytesLike> | null
    ): ExecutionAllowedEventFilter;

    "ExecutionDenied(address,bytes4)"(
      account?: PromiseOrValue<string> | null,
      method?: PromiseOrValue<BytesLike> | null
    ): ExecutionDeniedEventFilter;
    ExecutionDenied(
      account?: PromiseOrValue<string> | null,
      method?: PromiseOrValue<BytesLike> | null
    ): ExecutionDeniedEventFilter;

    "FunctionSignatureApprovalChanged(address,bytes4,bool)"(
      dex?: PromiseOrValue<string> | null,
      functionSignature?: PromiseOrValue<BytesLike> | null,
      approved?: PromiseOrValue<boolean> | null
    ): FunctionSignatureApprovalChangedEventFilter;
    FunctionSignatureApprovalChanged(
      dex?: PromiseOrValue<string> | null,
      functionSignature?: PromiseOrValue<BytesLike> | null,
      approved?: PromiseOrValue<boolean> | null
    ): FunctionSignatureApprovalChangedEventFilter;

    "MultiSwapped(bytes32,address,address,address,address,tuple[])"(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      recipient?: null,
      swapInfo?: null
    ): MultiSwappedEventFilter;
    MultiSwapped(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      recipient?: null,
      swapInfo?: null
    ): MultiSwappedEventFilter;

    "MultiTokenBridgeTransferStarted(bytes32,address,address,address,tuple[])"(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      bridgeData?: null
    ): MultiTokenBridgeTransferStartedEventFilter;
    MultiTokenBridgeTransferStarted(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      bridgeData?: null
    ): MultiTokenBridgeTransferStartedEventFilter;

    "SelectorToInfoUpdated(address[],bytes4[],tuple[])"(
      routers?: null,
      selectors?: null,
      info?: null
    ): SelectorToInfoUpdatedEventFilter;
    SelectorToInfoUpdated(
      routers?: null,
      selectors?: null,
      info?: null
    ): SelectorToInfoUpdatedEventFilter;

    "SetDzapFixedNativeFeeAmount(uint256)"(
      fee?: null
    ): SetDzapFixedNativeFeeAmountEventFilter;
    SetDzapFixedNativeFeeAmount(
      fee?: null
    ): SetDzapFixedNativeFeeAmountEventFilter;

    "SetDzapTokenFee(uint256)"(fee?: null): SetDzapTokenFeeEventFilter;
    SetDzapTokenFee(fee?: null): SetDzapTokenFeeEventFilter;

    "SetFixedNativeFee(uint256)"(fee?: null): SetFixedNativeFeeEventFilter;
    SetFixedNativeFee(fee?: null): SetFixedNativeFeeEventFilter;

    "SetIntegrator(address,uint8[],tuple[])"(
      integrator?: null,
      feeType?: null,
      info?: null
    ): SetIntegratorEventFilter;
    SetIntegrator(
      integrator?: null,
      feeType?: null,
      info?: null
    ): SetIntegratorEventFilter;

    "SetMaxPlatformFee(uint256)"(fee?: null): SetMaxPlatformFeeEventFilter;
    SetMaxPlatformFee(fee?: null): SetMaxPlatformFeeEventFilter;

    "SetPlatformFee(uint256)"(fee?: null): SetPlatformFeeEventFilter;
    SetPlatformFee(fee?: null): SetPlatformFeeEventFilter;

    "SwapBridgeTransferStarted(bytes32,address,address,address,tuple[],tuple[])"(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      bridgeData?: null,
      swapInfo?: null
    ): SwapBridgeTransferStartedEventFilter;
    SwapBridgeTransferStarted(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      bridgeData?: null,
      swapInfo?: null
    ): SwapBridgeTransferStartedEventFilter;

    "Swapped(bytes32,address,address,address,address,tuple)"(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      recipient?: null,
      swapInfo?: null
    ): SwappedEventFilter;
    Swapped(
      transactionId?: null,
      integrator?: PromiseOrValue<string> | null,
      sender?: PromiseOrValue<string> | null,
      refundee?: null,
      recipient?: null,
      swapInfo?: null
    ): SwappedEventFilter;
  };

  estimateGas: {
    addDex(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    addressCanExecuteMethod(
      _selector: PromiseOrValue<BytesLike>,
      _executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    batchAddDex(
      _dexs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchRemoveDex(
      _dexs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    batchSetFunctionApprovalBySignature(
      _dexs: PromiseOrValue<string>[],
      _signatures: PromiseOrValue<BytesLike>[],
      _approval: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bridge(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct,
      _genericData: CrossChainDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    bridgeMultipleTokens(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct[],
      _genericData: CrossChainDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    calcFixedNativeFees(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    calcTokenFees(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getSelectorInfo(
      _router: PromiseOrValue<string>,
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    integratorFeeInfo(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isContractApproved(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isFunctionApproved(
      _dex: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    isIntegratorAllowed(
      _integrator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    maxFixedNativeFeeAmount(overrides?: CallOverrides): Promise<BigNumber>;

    maxTokenFee(overrides?: CallOverrides): Promise<BigNumber>;

    multiSwap(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    multiSwapWithoutRevert(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    protocolFeeVault(overrides?: CallOverrides): Promise<BigNumber>;

    removeDex(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    removeIntegrator(
      _integrator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setBatchCanExecute(
      _selector: PromiseOrValue<BytesLike>[],
      _executor: PromiseOrValue<string>[],
      _canExecute: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setCanExecute(
      _selector: PromiseOrValue<BytesLike>,
      _executor: PromiseOrValue<string>,
      _canExecute: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setFunctionApprovalBySignature(
      _dex: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      _approval: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setIntegratorInfo(
      _integrator: PromiseOrValue<string>,
      _feeTypes: PromiseOrValue<BigNumberish>[],
      _feeInfo: FeeInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setProtocolFeeVault(
      _protocolFeeVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swap(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    swapAndBridge(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct[],
      _swapData: SwapDataStruct[],
      _genericData: CrossChainDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    updateSelectorInfo(
      _routers: PromiseOrValue<string>[],
      _selectors: PromiseOrValue<BytesLike>[],
      _infos: CallToFunctionInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    addDex(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    addressCanExecuteMethod(
      _selector: PromiseOrValue<BytesLike>,
      _executor: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    batchAddDex(
      _dexs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchRemoveDex(
      _dexs: PromiseOrValue<string>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    batchSetFunctionApprovalBySignature(
      _dexs: PromiseOrValue<string>[],
      _signatures: PromiseOrValue<BytesLike>[],
      _approval: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bridge(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct,
      _genericData: CrossChainDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    bridgeMultipleTokens(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct[],
      _genericData: CrossChainDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    calcFixedNativeFees(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    calcTokenFees(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      _amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getSelectorInfo(
      _router: PromiseOrValue<string>,
      _selector: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    integratorFeeInfo(
      _integrator: PromiseOrValue<string>,
      _feeType: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isContractApproved(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isFunctionApproved(
      _dex: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    isIntegratorAllowed(
      _integrator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxFixedNativeFeeAmount(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    maxTokenFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    multiSwap(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    multiSwapWithoutRevert(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    protocolFeeVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    removeDex(
      _dex: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    removeIntegrator(
      _integrator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setBatchCanExecute(
      _selector: PromiseOrValue<BytesLike>[],
      _executor: PromiseOrValue<string>[],
      _canExecute: PromiseOrValue<boolean>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setCanExecute(
      _selector: PromiseOrValue<BytesLike>,
      _executor: PromiseOrValue<string>,
      _canExecute: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setFunctionApprovalBySignature(
      _dex: PromiseOrValue<string>,
      _signature: PromiseOrValue<BytesLike>,
      _approval: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setIntegratorInfo(
      _integrator: PromiseOrValue<string>,
      _feeTypes: PromiseOrValue<BigNumberish>[],
      _feeInfo: FeeInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setProtocolFeeVault(
      _protocolFeeVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swap(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _recipient: PromiseOrValue<string>,
      _data: SwapDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    swapAndBridge(
      _transactionId: PromiseOrValue<BytesLike>,
      _integrator: PromiseOrValue<string>,
      _refundee: PromiseOrValue<string>,
      _bridgeData: BridgeDataStruct[],
      _swapData: SwapDataStruct[],
      _genericData: CrossChainDataStruct[],
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      _newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    updateSelectorInfo(
      _routers: PromiseOrValue<string>[],
      _selectors: PromiseOrValue<BytesLike>[],
      _infos: CallToFunctionInfoStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
