export const CONTRACTS_PATH = {
  DZapDiamond: 'contracts/DZapDiamond.sol:DZapDiamond',
  DiamondCutFacet:
    'contracts/Shared/Facets/DiamondCutFacet.sol:DiamondCutFacet',
  DiamondInit: 'contracts/Shared/Facets/DiamondInit.sol:DiamondInit',
  DiamondLoupeFacet:
    'contracts/Shared/Facets/DiamondLoupeFacet.sol:DiamondLoupeFacet',
  OwnershipFacet: 'contracts/Shared/Facets/OwnershipFacet.sol:OwnershipFacet',
  AccessManagerFacet:
    'contracts/Shared/Facets/AccessManagerFacet.sol:AccessManagerFacet',
  WithdrawFacet: 'contracts/Shared/Facets/WithdrawFacet.sol:WithdrawFacet',
  FeesFacet: 'contracts/Shared/Facets/FeesFacet.sol:FeesFacet',
  DexManagerFacet:
    'contracts/Shared/Facets/DexManagerFacet.sol:DexManagerFacet',
  SwapFacet: 'contracts/Swap/Facets/SwapFacet.sol:SwapFacet',
  SwapTransferFacet:
    'contracts/Swap/Facets/SwapTransferFacet.sol:SwapTransferFacet',
  BatchSwapFacet: 'contracts/Swap/Facets/BatchSwapFacet.sol:BatchSwapFacet',
  BridgeManagerFacet:
    'contracts/Bridge/Facets/BridgeManagerFacet.sol:BridgeManagerFacet',
  CrossChainFacet:
    'contracts/Bridge/Facets/CrossChainFacet.sol:CrossChainFacet',
  BridgeDynamicTransferFacet:
    'contracts/Bridge/Facets/BridgeDynamicTransferFacet.sol:BridgeDynamicTransferFacet',
  BatchBridgeCallFacet:
    'contracts/Bridge/Facets/BatchBridgeCallFacet.sol:BatchBridgeCallFacet',
  RelayBridgeFacet:
    'contracts/Bridge/Facets/RelayBridgeFacet.sol:RelayBridgeFacet',
  GasZipFacet: 'contracts/Bridge/Facets/GasZipFacet.sol:GasZipFacet',
  DirectTransferAdapter:
    'contracts/Bridge/Adapters/DirectTransferAdapter.sol:DirectTransferAdapter',
  GasZipAdapter: 'contracts/Bridge/Adapters/GasZipAdapter.sol:GasZipAdapter',
  GenericBridgeAdapter:
    'contracts/Bridge/Adapters/GenericBridgeAdapter.sol:GenericBridgeAdapter',
  RelayBridgeAdapter:
    'contracts/Bridge/Adapters/RelayBridgeAdapter.sol:RelayBridgeAdapter',
}

export const CONTRACTS = {
  DiamondCutFacet: 'DiamondCutFacet',
  DiamondInit: 'DiamondInit',
  DZapDiamond: 'DZapDiamond',
  DiamondLoupeFacet: 'DiamondLoupeFacet',
  OwnershipFacet: 'OwnershipFacet',
  AccessManagerFacet: 'AccessManagerFacet',
  DexManagerFacet: 'DexManagerFacet',
  FeesFacet: 'FeesFacet',
  WithdrawFacet: 'WithdrawFacet',
  SwapFacet: 'SwapFacet',
  CrossChainFacet: 'CrossChainFacet',
  BridgeManagerFacet: 'BridgeManagerFacet',
  BridgeDynamicTransferFacet: 'BridgeDynamicTransferFacet',
  BatchBridgeCallFacet: 'BatchBridgeCallFacet',
  Create2Deployer: 'Create2Deployer',
  SwapTransferFacet: 'SwapTransferFacet',
  BatchSwapFacet: 'BatchSwapFacet',
  RelayBridgeFacet: 'RelayBridgeFacet',
  GasZipFacet: 'GasZipFacet',
  DirectTransferAdapter: 'DirectTransferAdapter',
  GasZipAdapter: 'GasZipAdapter',
  GenericBridgeAdapter: 'GenericBridgeAdapter',
  RelayBridgeAdapter: 'RelayBridgeAdapter',
  // ERC20: 'ERC20',
  ERC20: '@openzeppelin/contracts/token/ERC20/ERC20.sol:ERC20',
  WNATIVE: 'WNATIVE',
  Permit2: 'Permit2',
  CreateX: 'CreateX',
  Executor: 'Executor',
  Receiver: 'Receiver',
  ERC20Mock: 'ERC20Mock',
  ExchangeMock: 'ExchangeMock',
  BridgeMock: 'BridgeMock',
  MockGasZipRouter: 'MockGasZipRouter',
}

export const ERRORS = {
  InitReverted: 'InitReverted',
  AlreadyInitialized: 'AlreadyInitialized',
  OnlyContractOwner: 'OnlyContractOwner',
  CannotAuthorizeSelf: 'CannotAuthorizeSelf',
  UnAuthorized: 'UnAuthorized',
  ZeroAddress: 'ZeroAddress',
  ShareTooHigh: 'ShareTooHigh',
  FeeTooHigh: 'FeeTooHigh',
  InvalidFee: 'InvalidFee',
  IntegratorNotActive: 'IntegratorNotActive',
  InvalidContract: 'InvalidContract',
  IntegratorNotAllowed: 'IntegratorNotAllowed',
  InvalidAmount: 'InvalidAmount',
  ContractCallNotAllowed: 'ContractCallNotAllowed',
  NoSwapFromZeroBalance: 'NoSwapFromZeroBalance',
  InformationMismatch: 'InformationMismatch',
  NotAContract: 'NotAContract',
  CannotBridgeToSameNetwork: 'CannotBridgeToSameNetwork',
  InvalidReceiver: 'InvalidReceiver',
  UnAuthorizedCallToFunction: 'UnAuthorizedCallToFunction',
  BridgeCallFailed: 'BridgeCallFailed',
  SlippageTooLow: 'SlippageTooLow',
  UnauthorizedCaller: 'UnauthorizedCaller',
  SwapCallFailed: 'SwapCallFailed',
  BridgeNotAdded: 'BridgeNotAdded',
  UnAuthorizedCall: 'UnAuthorizedCall',
  InvalidLength: 'InvalidLength',
  InvalidSwapDetails: 'InvalidSwapDetails',
  AdapterNotAdded: 'AdapterNotAdded',
  NotNativeToken: 'NotNativeToken',
}

export const EVENTS = {
  DexAdded: 'DexAdded',
  DexRemoved: 'DexRemoved',
  FunctionSignatureApprovalChanged: 'FunctionSignatureApprovalChanged',
  OwnershipTransferred: 'OwnershipTransferred',
  LogWithdraw: 'LogWithdraw',
  Swapped: 'Swapped',
  MultiSwapped: 'MultiSwapped',
  AllSwapsFailed: 'AllSwapsFailed',
  SelectorToInfoUpdated: 'SelectorToInfoUpdated',
  BridgeTransferStarted: 'BridgeTransferStarted',
  MultiTokenBridgeTransferStarted: 'MultiTokenBridgeTransferStarted',
  SwapBridgeTransferStarted: 'SwapBridgeTransferStarted',
  ExecutorSet: 'ExecutorSet',
  RecoverGasSet: 'RecoverGasSet',
  DZapTransferRecovered: 'DZapTransferRecovered',
  TokensRecovered: 'TokensRecovered',
  TokenSwapped: 'TokenSwapped',
  BridgeAdded: 'BridgeAdded',
  BridgeRemoved: 'BridgeRemoved',
  BatchBridgeTransferStart: 'BatchBridgeTransferStart',
  SwappedSingleToken: 'SwappedSingleToken',
  BatchSwapAndBridgeTransferStart: 'BatchSwapAndBridgeTransferStart',
  AdaptersAdded: 'AdaptersAdded',
  AdaptersRemoved: 'AdaptersRemoved',
  GasZipBridgeTransferStarted: 'GasZipBridgeTransferStarted',
  GasZipSwapBridgeTransferStarted: 'GasZipSwapBridgeTransferStarted',
  Deposit: 'Deposit', // gasZip
}

export const FunctionNames = {
  AddDex: 'addDex',
  BatchAddDex: 'batchAddDex',
  RemoveDex: 'removeDex',
  BatchRemoveDex: 'batchRemoveDex',
  SetFunctionApprovalBySignature: 'setFunctionApprovalBySignature',
  BatchSetFunctionApprovalBySignature: 'batchSetFunctionApprovalBySignature',
  SetProtocolFeeVault: 'setProtocolFeeVault',
  SetIntegratorInfo: 'setIntegratorInfo',
  RemoveIntegrator: 'removeIntegrator',
  UpdateSelectorInfo: 'updateSelectorInfo',
  AddAggregatorsAndBridges: 'addAggregatorsAndBridges',
  RemoveAggregatorsAndBridges: 'removeAggregatorsAndBridges',
  AddAdapters: 'addAdapters',
  RemoveAdapters: 'removeAdapters',
}
