/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../common";

export type SwapDataStruct = {
  callTo: PromiseOrValue<string>;
  approveTo: PromiseOrValue<string>;
  from: PromiseOrValue<string>;
  to: PromiseOrValue<string>;
  fromAmount: PromiseOrValue<BigNumberish>;
  minToAmount: PromiseOrValue<BigNumberish>;
  swapCallData: PromiseOrValue<BytesLike>;
  permit: PromiseOrValue<BytesLike>;
};

export type SwapDataStructOutput = [
  string,
  string,
  string,
  string,
  BigNumber,
  BigNumber,
  string,
  string
] & {
  callTo: string;
  approveTo: string;
  from: string;
  to: string;
  fromAmount: BigNumber;
  minToAmount: BigNumber;
  swapCallData: string;
  permit: string;
};

export interface IExecutorInterface extends utils.Interface {
  functions: {
    "swapAndCompleteBridgeTokens(bytes32,address,(address,address,address,address,uint256,uint256,bytes,bytes))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "swapAndCompleteBridgeTokens"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "swapAndCompleteBridgeTokens",
    values: [PromiseOrValue<BytesLike>, PromiseOrValue<string>, SwapDataStruct]
  ): string;

  decodeFunctionResult(
    functionFragment: "swapAndCompleteBridgeTokens",
    data: BytesLike
  ): Result;

  events: {
    "DzapTransferCompleted(bytes32,address,address,address,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "DzapTransferCompleted"): EventFragment;
}

export interface DzapTransferCompletedEventObject {
  transactionId: string;
  from: string;
  to: string;
  receiver: string;
  amount: BigNumber;
  timestamp: BigNumber;
}
export type DzapTransferCompletedEvent = TypedEvent<
  [string, string, string, string, BigNumber, BigNumber],
  DzapTransferCompletedEventObject
>;

export type DzapTransferCompletedEventFilter =
  TypedEventFilter<DzapTransferCompletedEvent>;

export interface IExecutor extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IExecutorInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    swapAndCompleteBridgeTokens(
      _transactionId: PromiseOrValue<BytesLike>,
      _receiver: PromiseOrValue<string>,
      _swapData: SwapDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  swapAndCompleteBridgeTokens(
    _transactionId: PromiseOrValue<BytesLike>,
    _receiver: PromiseOrValue<string>,
    _swapData: SwapDataStruct,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    swapAndCompleteBridgeTokens(
      _transactionId: PromiseOrValue<BytesLike>,
      _receiver: PromiseOrValue<string>,
      _swapData: SwapDataStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "DzapTransferCompleted(bytes32,address,address,address,uint256,uint256)"(
      transactionId?: PromiseOrValue<BytesLike> | null,
      from?: null,
      to?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): DzapTransferCompletedEventFilter;
    DzapTransferCompleted(
      transactionId?: PromiseOrValue<BytesLike> | null,
      from?: null,
      to?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): DzapTransferCompletedEventFilter;
  };

  estimateGas: {
    swapAndCompleteBridgeTokens(
      _transactionId: PromiseOrValue<BytesLike>,
      _receiver: PromiseOrValue<string>,
      _swapData: SwapDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    swapAndCompleteBridgeTokens(
      _transactionId: PromiseOrValue<BytesLike>,
      _receiver: PromiseOrValue<string>,
      _swapData: SwapDataStruct,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
