import { CONTRACTS } from '../../../constants'
import { DIAMOND_LOUPE_FACET_DEPLOYMENT_CONFIG } from './diamondLoupeFacet'
import { OWNERSHIP_FACET_DEPLOYMENT_CONFIG } from './ownershipFacet'
import { ACCESS_MANAGER_FACET_DEPLOYMENT_CONFIG } from './AccessManagerFacet'
import { DEX_MANAGER_FACET_DEPLOYMENT_CONFIG } from './dexManagerFacet'
import { BRIDGE_MANAGER_FACET_DEPLOYMENT_CONFIG } from './bridgeManagerFacet'
import { FEES_FACET_DEPLOYMENT_CONFIG } from './feesFacet'
import { WITHDRAW_FACET_DEPLOYMENT_CONFIG } from './withdrawFacet'
import { SWAP_FACET_DEPLOYMENT_CONFIG } from './swapFacet'
import { SWAP_TRANSFER_FACET_DEPLOYMENT_CONFIG } from './swapTransferFacet'
import { BATCH_SWAP_FACET_DEPLOYMENT_CONFIG } from './batchSwapFacet'
import { CROSS_CHAIN_FACET_DEPLOYMENT_CONFIG } from './crossChainFacet'
import { BRIDGE_DYNAMIC_TRANSFER_FACET_DEPLOYMENT_CONFIG } from './bridgeDynamicTransferFacet'
import { BATCH_BRIDGE_CALL_FACET_DEPLOYMENT_CONFIG } from './batchBridgeCallFacet'
import { RELAY_BRIDGE_FACET_DEPLOYMENT_CONFIG } from './relayBridgeFacet'
import { GAS_ZIP_FACET_DEPLOYMENT_CONFIG } from './gasZipFacet'
import { DIAMOND_INIT_DEPLOYMENT_CONFIG } from './diamondInit'
import { Create3DeploymentConfig } from '../../../types'

export const FACETS_DEPLOYMENT_CONFIG: {
  [key: string]: Create3DeploymentConfig[]
} = {
  [CONTRACTS.DiamondLoupeFacet]: DIAMOND_LOUPE_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.OwnershipFacet]: OWNERSHIP_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.AccessManagerFacet]: ACCESS_MANAGER_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.DexManagerFacet]: DEX_MANAGER_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.BridgeManagerFacet]: BRIDGE_MANAGER_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.FeesFacet]: FEES_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.WithdrawFacet]: WITHDRAW_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.SwapFacet]: SWAP_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.SwapTransferFacet]: SWAP_TRANSFER_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.BatchSwapFacet]: BATCH_SWAP_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.CrossChainFacet]: CROSS_CHAIN_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.BridgeDynamicTransferFacet]:
    BRIDGE_DYNAMIC_TRANSFER_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.BatchBridgeCallFacet]: BATCH_BRIDGE_CALL_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.RelayBridgeFacet]: RELAY_BRIDGE_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.GasZipFacet]: GAS_ZIP_FACET_DEPLOYMENT_CONFIG,
  [CONTRACTS.DiamondInit]: DIAMOND_INIT_DEPLOYMENT_CONFIG,
}
