/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAccessManagerFacet } from "./IAccessManagerFacet";
export type { IOwnershipFacet } from "./IOwnershipFacet";
