/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAccessManagerFacet,
  IAccessManagerFacetInterface,
} from "../../../../contracts/Shared/Interfaces/IAccessManagerFacet";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes4",
        name: "method",
        type: "bytes4",
      },
    ],
    name: "ExecutionAllowed",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "account",
        type: "address",
      },
      {
        indexed: true,
        internalType: "bytes4",
        name: "method",
        type: "bytes4",
      },
    ],
    name: "ExecutionDenied",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_selector",
        type: "bytes4",
      },
      {
        internalType: "address",
        name: "_executor",
        type: "address",
      },
    ],
    name: "addressCanExecuteMethod",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "bytes4",
        name: "_selector",
        type: "bytes4",
      },
      {
        internalType: "address",
        name: "_executor",
        type: "address",
      },
      {
        internalType: "bool",
        name: "_canExecute",
        type: "bool",
      },
    ],
    name: "setCanExecute",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAccessManagerFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IAccessManagerFacetInterface {
    return new utils.Interface(_abi) as IAccessManagerFacetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAccessManagerFacet {
    return new Contract(address, _abi, signerOrProvider) as IAccessManagerFacet;
  }
}
