/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAccessManagerFacet,
  IAccessManagerFacetInterface,
} from "../../../../../contracts/Shared/Interfaces/IOwnershipFacet.sol/IAccessManagerFacet";

const _abi = [
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "owner_",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_newOwner",
        type: "address",
      },
    ],
    name: "transferOwnership",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IAccessManagerFacet__factory {
  static readonly abi = _abi;
  static createInterface(): IAccessManagerFacetInterface {
    return new utils.Interface(_abi) as IAccessManagerFacetInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAccessManagerFacet {
    return new Contract(address, _abi, signerOrProvider) as IAccessManagerFacet;
  }
}
