/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IAccessManagerFacet__factory } from "./IAccessManagerFacet__factory";
export { IOwnershipFacet__factory } from "./IOwnershipFacet__factory";
