import { NODE_ENV_VAR_NAMES } from '../constants'
import { ApiType, Networks, ZKChainConfig } from '../types'
import { getZkChainConfig } from '../utils/networkUtils'

export enum RPC_TYPE {
  ALCHEMY,
  INFURA,
  BLAST_API,
  OTHER,
}

export enum CHAIN_IDS {
  APE_CHAIN = 33139,
  ARBITRUM_MAINNET = 42161,
  ARBITRUM_NOVA = 42170,
  AURORA_MAINNET = 1313161554,
  AURORA_TESTNET = 1313161555,
  AVALANCHE_MAINNET = 43114,
  AVALANCHE_TESTNET = 43113,
  ABSTRACT_MAINNET = 2741,
  ABSTRACT_TESTNET = 11124,
  ARTHERA = 10242,
  AI_LAYER = 2649,
  BAHAMUT_MAINNET = 5165,
  BASE_MAINNET = 8453,
  BASE_SEPOLIA = 84532,
  BEVM_MAINNET = 11501,
  BLAST_MAINNET = 81457,
  BOB_MAINNET = 60808,
  BOBA_AVALANCHE = 43288,
  BOBA_BNB = 56288,
  BOBA_ETH = 288,
  BOBA_RINKEBY = 28,
  BERACHAIN_MAINNET = 80094,
  BSC_MAINNET = 56,
  BSC_TESTNET = 97,
  BTC_MAINNET = 3652501241,
  BTC_MUTINY = 2782866891,
  BTC_TESTNET4 = 675223068,
  B2SQUARE_NETWORK = 223,
  BITLAYER = 200901,
  BOUNCE_BIT = 6001,
  BI_FROST = 3068,
  CELO_MAINNET = 42220,
  CONFLUX_E_SPACE_MAINNET = 1030,
  CONFLUX_E_SPACE_TESTNET = 71,
  CORE_MAINNET = 1116,
  CRONOS_MAINNET = 25,
  CRONOS_ZKEVM_MAINNET = 388,
  DOGECHAIN_MAINNET = 2000,
  ETH_KOVAN = 42,
  ETH_MAINNET = 1,
  ETH_RINKEBY = 4,
  ETH_SEPOLIA = 11155111,
  ECLIPSE = 1000002,
  FANTOM_MAINNET = 250,
  FILECOIN_MAINNET = 314,
  FUSE = 122,
  FRAXTAL = 252,
  FIRE_MAINNET = 995,
  FLARE = 14,
  GANACHE = 1337,
  GNOSIS_MAINNET = 100,
  GOAT = 2345,
  GRAVITY = 1625,
  HARDHAT = 31337,
  HOLESKY_TESTNET = 17000,
  HECO_MAINNET = 128,
  HECO_TESTNET = 256,
  HYPER_EVM = 999,
  HEMI = 43111,
  INK = 57073,
  IMMUTABLE_ZKEVM = 13371,
  IOTA_EVM = 8822,
  KAVA_MAINNET = 2222,
  KROMA = 255,
  KYOTO_MAINNET = 1997,
  KAIA = 8217,
  LINEA_MAINNET = 59144,
  LINEA_TESTNET = 59140,
  LISK_MAINNET = 1135,
  LENS = 232,
  LENS_TESTNET = 37111,
  MANTA_MAINNET = 169,
  MANTLE_MAINNET = 5000,
  MANTLE_TESTNET = 5001,
  MERLIN_MAINNET = 4200,
  METIS_MAINNET = 1088,
  METAL_L2 = 1750,
  MILKOMEDA_DEVNET = 200101,
  MILKOMEDA_MAINNET = 2001,
  MINT = 185,
  MORPH = 2818,
  MODE_MAINNET = 34443,
  MOONBEAM_MAINNET = 1284,
  MOONRIVER = 1285,
  MONAD = 143,
  MONAD_TESTNET = 10143,
  ONTOLOGY = 58,
  OASIS_SAPPHIRE_MAINNET = 23294,
  OKEX_TESTNET = 65,
  OKX_MAINNET = 66,
  OKX_X1_TESTNET = 195,
  OPBNB_MAINNET = 204,
  OPTIMISM_MAINNET = 10,
  OP_SEPOLIA = 11155420,
  POLYGON_MAINNET = 137,
  POLYGON_MUMBAI = 80001,
  POLYGON_ZK_EVM_MAINNET = 1101,
  POLYGON_ZK_EVM_TESTNET = 1442,
  PULSE_CHAIN = 369,
  ROOLUX_MAINNET = 570,
  ROOTSTOCK_MAINNET = 30,
  RONIN = 2020,
  SAAKURU_MAINNET = 7225878,
  SCROLL_MAINNET = 534352,
  SCROLL_SEPOLIA = 534351,
  SEI_EVM_MAINNET = 1329,
  SHARDEUM_TESTNET_2 = 8081,
  SONIC_MAINNET = 146,
  SONEIUM_MAINNET = 1868,
  SUPER_POSITION = 55244,
  SUPERSEED = 5330,
  STORY = 1514,
  SWELLCHAIN = 1923,
  TAIKO_MAINNET = 167000,
  TELOS_MAINNET = 40,
  TELOS_TESTNET = 41,
  TON_MAINNET = 8888888,
  TRON_MAINNET = 728126428,
  TRON_TESTNET = 2494104990,
  UNICHAIN = 130,
  UNICHAIN_SEPOLIA = 1301,
  VELAS = 106,
  WORLD_CHAIN = 480,
  X_LAYER_MAINNET = 196,
  X_LAYER_TESTNET = 195,
  ZETACHAIN_ATHENS_2 = 7001,
  ZETACHAIN_MAINNET = 7000,
  ZKLINK_MAINNET = 810180,
  ZKSYNC_MAINNET = 324,
  ZKSYNC_SEPOLIA_TESTNET = 300,
  ZKFAIR = 42766,
}

// const SourcifyUrls = [
//   "https://sourcify.dev/server",
//   "https://repo.sourcify.dev",
// ];
export const SourcifyVerificationConfig = {
  [CHAIN_IDS.MONAD_TESTNET]: {
    apiUrl: 'https://sourcify-api-monad.blockvision.org',
    browserUrl: 'https://testnet.monadexplorer.com',
  },
  [CHAIN_IDS.RONIN]: {
    apiUrl: 'https://sourcify.roninchain.com/server',
    browserUrl: 'https://app.roninchain.com',
  },
  [CHAIN_IDS.HYPER_EVM]: {
    apiUrl: 'https://sourcify.parsec.finance',
    browserUrl: 'https://hyperscan.gas.zip',
  },
  [CHAIN_IDS.BOUNCE_BIT]: {
    apiUrl: 'https://sourcify-api.bbscan.io',
    browserUrl: 'https://bbscan.io',
  },
  [CHAIN_IDS.TELOS_MAINNET]: {
    apiUrl: 'https://repo.sourcify.dev', // default
    browserUrl: 'https://teloscan.io',
  },
}

export const ZK_EVM_CHAINS: { [key in CHAIN_IDS]?: ZKChainConfig } = {
  [CHAIN_IDS.ZKSYNC_SEPOLIA_TESTNET]: {
    name: 'zkSync Sepolia Testnet',
    shortName: 'zksyncTestnet',
    shortNameZk: 'zkSyncZkTestnet',
    verifyKeyName: 'zksyncsepolia',
    verifyURL: 'https://explorer.sepolia.era.zksync.dev/contract_verification',
    isTestnet: true,
  },
  [CHAIN_IDS.ABSTRACT_TESTNET]: {
    name: 'Abstract Testnet',
    shortName: 'abstractTestnet',
    shortNameZk: 'abstractZkTestnet',
    // verifyURL: "https://api-sepolia.abscan.org/api",
    isTestnet: true,
  },
  [CHAIN_IDS.LENS_TESTNET]: {
    name: 'Lens Testnet',
    shortName: 'lensTestnet',
    shortNameZk: 'lensZkTestnet',
    isTestnet: true,
    verifyURL:
      'https://block-explorer-verify.testnet.lens.xyz/contract_verification',
  },
  [CHAIN_IDS.ZKSYNC_MAINNET]: {
    name: 'zkSync Mainnet',
    shortName: 'zksync',
    shortNameZk: 'zkSyncZk',
    verifyKeyName: 'zksyncmainnet',
    verifyURL:
      'https://zksync2-mainnet-explorer.zksync.io/contract_verification',
    isTestnet: false,
  },
  [CHAIN_IDS.ABSTRACT_MAINNET]: {
    name: 'Abstract Mainnet',
    shortName: 'abstract',
    shortNameZk: 'abstractZk',
    // verifyURL: "https://api.abscan.org/api",
    isTestnet: false,
  },
  [CHAIN_IDS.LENS]: {
    name: 'Lens Mainnet',
    shortName: 'lens',
    shortNameZk: 'lensZk',
    isTestnet: false,
    verifyURL: 'https://verify.lens.xyz/contract_verification',
  },
  [CHAIN_IDS.CRONOS_ZKEVM_MAINNET]: {
    name: 'Cronos ZKEVM Mainnet',
    shortName: 'cronosZkEvm',
    shortNameZk: 'cronosZk',
    isTestnet: false,
  },
}

export const NETWORKS: Networks = {
  [CHAIN_IDS.GANACHE]: {
    chainId: CHAIN_IDS.GANACHE,
    chainName: 'Ganache',
    shortName: 'ganache',
    rpcUrl: [''],
    explorerUrl: '',
    apiUrl: '',
    apiType: ApiType.OTHER,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.HARDHAT]: {
    chainId: CHAIN_IDS.HARDHAT,
    chainName: 'Hardhat',
    shortName: 'hardhat',
    rpcUrl: [''],
    explorerUrl: '',
    apiUrl: '',
    apiType: ApiType.OTHER,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ETH_MAINNET]: {
    chainId: CHAIN_IDS.ETH_MAINNET,
    chainName: 'Ethereum Mainnet',
    shortName: 'ethereum',
    rpcUrl: [
      `https://eth-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://rpc.ankr.com/eth',
      'https://eth.llamarpc.com',
    ],
    explorerUrl: 'https://etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ETH_SEPOLIA]: {
    chainId: CHAIN_IDS.ETH_SEPOLIA,
    chainName: 'Sepolia Testnet',
    shortName: 'ethSepolia',
    rpcUrl: [
      'https://eth-sepolia.public.blastapi.io',
      'https://eth-sepolia.g.alchemy.com/v2/demo',
      'https://ethereum-sepolia-rpc.publicnode.com',
      'https://rpc.sepolia.org',
    ],
    explorerUrl: 'https://sepolia.etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=11155111',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.HOLESKY_TESTNET]: {
    chainId: CHAIN_IDS.HOLESKY_TESTNET,
    chainName: 'Holesky Testnet',
    shortName: 'holesky',
    rpcUrl: ['https://rpc.sepolia.org'],
    explorerUrl: 'https://holesky.etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=17000',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ARBITRUM_MAINNET]: {
    chainId: CHAIN_IDS.ARBITRUM_MAINNET,
    chainName: 'Arbitrum One',
    shortName: 'arbitrumOne',
    rpcUrl: [
      `https://arb-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://arb1.arbitrum.io/rpc',
      `https://arbitrum-mainnet.infura.io/v3/${NODE_ENV_VAR_NAMES.INFURA_API_KEY}`,
      'https://arbitrum-one-rpc.publicnode.com',
    ],
    explorerUrl: 'https://arbiscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=42161',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.OPTIMISM_MAINNET]: {
    chainId: CHAIN_IDS.OPTIMISM_MAINNET,
    shortName: 'optimism',
    chainName: 'Optimism Mainnet',
    rpcUrl: [
      `https://opt-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
    ],
    explorerUrl: 'https://optimistic.etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=10',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.OP_SEPOLIA]: {
    chainId: CHAIN_IDS.OP_SEPOLIA,
    shortName: 'opSepolia',
    chainName: 'Op Sepolia',
    rpcUrl: [
      'https://sepolia.optimism.io',
      `https://endpoints.omniatech.io/v1/op/sepolia/public`,
    ],
    explorerUrl: 'https://sepolia-optimism.etherscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=11155420',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ZKSYNC_MAINNET]: {
    chainId: CHAIN_IDS.ZKSYNC_MAINNET,
    chainName: 'ZkSync Era',
    shortName: getZkChainConfig(CHAIN_IDS.ZKSYNC_MAINNET).shortName,
    rpcUrl: ['https://mainnet.era.zksync.io', 'https://zksync.drpc.org'],
    explorerUrl: 'https://explorer.zksync.io',
    // apiUrl: "https://api.etherscan.io/v2/api?chainid=324",
    // apiUrl: "https://zksync2-mainnet-explorer.zksync.io/contract_verification",
    // apiType: ApiType.ETHERSCAN_V2,
    apiType: ApiType.ETHERSCAN_V1,
    apiKeyName: NODE_ENV_VAR_NAMES.ZKSYNC_API_KEY,
    verifyKeyName: getZkChainConfig(CHAIN_IDS.ZKSYNC_MAINNET).verifyKeyName,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ZKSYNC_SEPOLIA_TESTNET]: {
    chainId: CHAIN_IDS.ZKSYNC_SEPOLIA_TESTNET,
    chainName: 'ZkSync Sepolia Mainnet',
    shortName: getZkChainConfig(CHAIN_IDS.ZKSYNC_SEPOLIA_TESTNET).shortName,
    rpcUrl: ['https://sepolia.era.zksync.dev'],
    explorerUrl: 'https://sepolia-era.zksync.network',
    // apiUrl: "https://api.etherscan.io/v2/api?chainid=300",
    // apiUrl: "https://explorer.sepolia.era.zksync.dev/contract_verification",
    // apiType: ApiType.NONE,
    apiType: ApiType.ETHERSCAN_V1,
    apiKeyName: NODE_ENV_VAR_NAMES.ZKSYNC_API_KEY,
    verifyKeyName: getZkChainConfig(CHAIN_IDS.ZKSYNC_SEPOLIA_TESTNET)
      .verifyKeyName,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.BASE_MAINNET]: {
    chainId: CHAIN_IDS.BASE_MAINNET,
    chainName: 'Base',
    shortName: 'base',
    rpcUrl: [
      `https://base-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://mainnet.base.org/',
    ],
    explorerUrl: 'https://basescan.org',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=8453',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.BASE_SEPOLIA]: {
    chainId: CHAIN_IDS.BASE_SEPOLIA,
    chainName: 'Base Sepolia',
    shortName: 'baseSepolia',
    rpcUrl: [
      'https://sepolia.base.org',
      'https://base-sepolia.gateway.tenderly.co',
      `https://base-sepolia.drpc.org`,
    ],
    explorerUrl: 'https://sepolia.basescan.org/',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=84532',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.POLYGON_MAINNET]: {
    chainId: CHAIN_IDS.POLYGON_MAINNET,
    chainName: 'Polygon Mainnet',
    shortName: 'polygon',
    rpcUrl: [
      `https://polygon-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://polygon-rpc.com/',
      'https://rpc-mainnet.matic.network',
      'https://matic-mainnet.chainstacklabs.com',
      'https://rpc-mainnet.maticvigil.com',
    ],
    explorerUrl: 'https://polygonscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=137',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'POL', symbol: 'POL', decimals: 18 },
  },
  [CHAIN_IDS.BSC_MAINNET]: {
    chainId: CHAIN_IDS.BSC_MAINNET,
    chainName: 'Binance Smart Chain',
    shortName: 'bsc',
    rpcUrl: [
      'https://bsc-dataseed1.bnbchain.org',
      'https://bsc-dataseed2.bnbchain.org',
      'https://bscrpc.com',
    ],
    explorerUrl: 'https://bscscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=56',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'BNB Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
  },
  [CHAIN_IDS.BSC_TESTNET]: {
    chainId: CHAIN_IDS.BSC_TESTNET,
    chainName: 'Binance Smart Chain Testnet',
    shortName: 'bscTestnet',
    rpcUrl: [
      'https://data-seed-prebsc-1-s1.bnbchain.org:8545',
      'https://data-seed-prebsc-2-s1.bnbchain.org:8545',
      'https://bsc-testnet.public.blastapi.io',
    ],
    explorerUrl: 'https://testnet.bscscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=97',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'BNB Chain Native Token',
      symbol: 'BNB',
      decimals: 18,
    },
  },
  [CHAIN_IDS.AVALANCHE_MAINNET]: {
    chainId: CHAIN_IDS.AVALANCHE_MAINNET,
    chainName: 'Avalanche C-Chain',
    shortName: 'avalanche',
    rpcUrl: [
      `https://avax-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://api.avax.network/ext/bc/C/rpc',
      'https://avalanche-c-chain-rpc.publicnode.com',
    ],
    explorerUrl: 'https://snowscan.xyz',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=43114',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Avalanche', symbol: 'AVAX', decimals: 18 },
  },
  [CHAIN_IDS.MANTA_MAINNET]: {
    chainId: CHAIN_IDS.MANTA_MAINNET,
    chainName: 'Manta Pacific',
    shortName: 'manta',
    rpcUrl: [
      'https://pacific-rpc.manta.network/http',
      'https://manta-pacific.drpc.org',
    ],
    explorerUrl: 'https://pacific-explorer.manta.network',
    apiUrl: 'https://pacific-explorer.manta.network/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.SCROLL_MAINNET]: {
    chainId: CHAIN_IDS.SCROLL_MAINNET,
    chainName: 'Scroll Mainnet',
    shortName: 'scroll',
    rpcUrl: ['https://rpc.scroll.io'],
    explorerUrl: 'https://scrollscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=534352',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.LINEA_MAINNET]: {
    chainId: CHAIN_IDS.LINEA_MAINNET,
    chainName: 'Linea Mainnet',
    shortName: 'linea',
    rpcUrl: [
      `https://linea-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
    ],
    explorerUrl: 'https://lineascan.build',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=59144',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.MANTLE_MAINNET]: {
    chainId: CHAIN_IDS.MANTLE_MAINNET,
    chainName: 'Mantle Mainnet',
    shortName: 'mantle',
    rpcUrl: [
      'https://rpc.mantle.xyz',
      `https://mantle-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://mantle-mainnet.blastapi.io',
    ],
    // explorerUrl: 'https://explorer.mantle.xyz/',
    // apiUrl: 'https://explorer.mantle.xyz/api',
    // apiType: ApiType.BLOCKSCOUT,
    explorerUrl: 'https://mantlescan.xyz',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=5000',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Mantle', symbol: 'MNT', decimals: 18 },
  },
  [CHAIN_IDS.TELOS_MAINNET]: {
    chainId: CHAIN_IDS.TELOS_MAINNET,
    chainName: 'Telos Mainnet',
    shortName: 'telos',
    rpcUrl: [
      'https://rpc.ankr.com/telos',
      'https://mainnet.telos.net/evm',
      'https://telos.drpc.org',
    ],
    explorerUrl: 'https://teloscan.io',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: { name: 'Telos', symbol: 'TLOS', decimals: 18 },
  },
  [CHAIN_IDS.CORE_MAINNET]: {
    chainId: CHAIN_IDS.CORE_MAINNET,
    chainName: 'Core',
    shortName: 'core',
    rpcUrl: [
      'https://rpc.coredao.org/',
      'https://rpc-core.icecreamswap.com',
      'https://core.drpc.org',
    ],
    explorerUrl: 'https://scan.coredao.org',
    apiUrl: 'https://openapi.coredao.org/api',
    apiType: ApiType.ETHERSCAN_V1,
    apiKeyName: NODE_ENV_VAR_NAMES.CORE_API_KEY,
    nativeCurrency: { name: 'CORE', symbol: 'CORE', decimals: 18 },
  },
  [CHAIN_IDS.ROOTSTOCK_MAINNET]: {
    chainId: CHAIN_IDS.ROOTSTOCK_MAINNET,
    chainName: 'Rootstock Mainnet',
    shortName: 'rootstock',
    rpcUrl: [
      'https://public-node.rsk.co',
      'https://rpc.ankr.com/rsk',
      'https://rootstock-mainnet.blastapi.io',
      'https://mycrypto.rsk.co',
    ],
    explorerUrl: 'https://rootstock.blockscout.com',
    apiUrl: 'https://rootstock.blockscout.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'Smart Bitcoin',
      symbol: 'RBTC',
      decimals: 18,
    },
  },
  [CHAIN_IDS.X_LAYER_MAINNET]: {
    chainId: CHAIN_IDS.X_LAYER_MAINNET,
    chainName: 'X-Layer Mainnet',
    shortName: 'xlayer',
    rpcUrl: ['https://xlayerrpc.okx.com', 'https://rpc.xlayer.tech'],
    explorerUrl: 'https://www.oklink.com/xlayer',
    apiUrl:
      'https://www.oklink.com/api/v5/explorer/contract/verify-source-code-plugin/XLAYER',
    apiType: ApiType.ETHERSCAN_V1,
    apiKeyName: NODE_ENV_VAR_NAMES.X_LAYER_API_KEY,
    nativeCurrency: {
      name: 'X Layer Global Utility Token',
      symbol: 'OKB',
      decimals: 18,
    },
  },
  [CHAIN_IDS.POLYGON_ZK_EVM_MAINNET]: {
    chainId: CHAIN_IDS.POLYGON_ZK_EVM_MAINNET,
    chainName: 'Polygon zkEVM Mainnet',
    shortName: 'polygonZk',
    rpcUrl: ['https://zkevm-rpc.com', 'https://polygon-zkevm.drpc.org'],
    explorerUrl: 'https://zkevm.polygonscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1101',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.MODE_MAINNET]: {
    chainId: CHAIN_IDS.MODE_MAINNET,
    chainName: 'Mode Mainnet',
    shortName: 'mode',
    rpcUrl: ['https://mainnet.mode.network', 'https://mode.drpc.org'],
    explorerUrl: 'https://explorer.mode.network',
    apiUrl: 'https://explorer.mode.network/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.METIS_MAINNET]: {
    chainId: CHAIN_IDS.METIS_MAINNET,
    chainName: 'Metis Andromeda',
    shortName: 'metis',
    rpcUrl: ['https://andromeda.metis.io/', 'https://metis.drpc.org'],
    explorerUrl: 'https://andromeda-explorer.metis.io',
    apiUrl: 'https://api.routescan.io/v2/network/mainnet/evm/1088/etherscan',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Metis', symbol: 'METIS', decimals: 18 },
  },
  [CHAIN_IDS.CELO_MAINNET]: {
    chainId: CHAIN_IDS.CELO_MAINNET,
    chainName: 'Celo',
    shortName: 'celo',
    rpcUrl: ['https://forno.celo.org'],
    explorerUrl: 'https://celoscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=42220',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'CELO', symbol: 'CELO', decimals: 18 },
  },
  [CHAIN_IDS.ZETACHAIN_MAINNET]: {
    chainId: CHAIN_IDS.ZETACHAIN_MAINNET,
    chainName: 'Zetachain Mainnet',
    shortName: 'zeta',
    rpcUrl: [
      'https://zetachain-mainnet.public.blastapi.io',
      'https://zetachain-evm.blockpi.network/v1/rpc/public',
    ],
    explorerUrl: 'https://zetachain.blockscout.com',
    apiUrl: 'https://zetachain.blockscout.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Zeta', symbol: 'ZETA', decimals: 18 },
  },
  [CHAIN_IDS.BLAST_MAINNET]: {
    chainId: CHAIN_IDS.BLAST_MAINNET,
    chainName: 'Blast',
    shortName: 'blast',
    rpcUrl: ['https://rpc.blast.io', 'https://rpc.ankr.com/blast'],
    explorerUrl: 'https://blastscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=81457',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.BOBA_ETH]: {
    chainId: CHAIN_IDS.BOBA_ETH,
    chainName: 'Boba ETH',
    shortName: 'bobaEth',
    rpcUrl: ['https://mainnet.boba.network'],
    explorerUrl: 'https://bobascan.com',
    apiUrl: 'https://api.routescan.io/v2/network/mainnet/evm/288/etherscan',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.FRAXTAL]: {
    chainId: CHAIN_IDS.FRAXTAL,
    chainName: 'Fraxtal',
    shortName: 'fraxtal',
    rpcUrl: ['https://rpc.frax.com'],
    explorerUrl: 'https://fraxscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=252',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'Frax Ether',
      symbol: 'frxETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.GRAVITY]: {
    chainId: CHAIN_IDS.GRAVITY,
    chainName: 'Gravity',
    shortName: 'gravity',
    rpcUrl: ['https://rpc.gravity.xyz', 'https://rpc.ankr.com/gravity'],
    explorerUrl: 'https://explorer.gravity.xyz',
    apiUrl: 'https://explorer.gravity.xyz/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Gravity', symbol: 'G', decimals: 18 },
  },
  [CHAIN_IDS.GNOSIS_MAINNET]: {
    chainId: CHAIN_IDS.GNOSIS_MAINNET,
    chainName: 'Gnosis Mainnet',
    shortName: 'gnosis',
    rpcUrl: ['https://gnosis-rpc.publicnode.com'],
    explorerUrl: 'https://gnosisscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=100',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'xDAI', symbol: 'XDAI', decimals: 18 },
  },
  [CHAIN_IDS.FUSE]: {
    chainId: CHAIN_IDS.FUSE,
    chainName: 'Fuse',
    shortName: 'fuse',
    rpcUrl: ['https://rpc.fuse.io'],
    explorerUrl: 'https://explorer.fuse.io',
    apiUrl: 'https://explorer.fuse.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Fuse', symbol: 'FUSE', decimals: 18 },
  },
  [CHAIN_IDS.FANTOM_MAINNET]: {
    chainId: CHAIN_IDS.FANTOM_MAINNET,
    chainName: 'Fantom Mainnet',
    shortName: 'fantom',
    rpcUrl: [
      'https://rpcapi.fantom.network',
      `https://fantom-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://rpc.ftm.tools',
      'https://fantom-rpc.publicnode.com',
      'https://fantom.drpc.org',
      'https://rpcapi.fantom.network',
    ],
    explorerUrl: 'https://ftmscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=250',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Fantom', symbol: 'FTM', decimals: 18 },
  },
  [CHAIN_IDS.MOONBEAM_MAINNET]: {
    chainId: CHAIN_IDS.MOONBEAM_MAINNET,
    chainName: 'Moonbeam Mainnet',
    shortName: 'moonbeam',
    rpcUrl: ['https://moonbeam.public.blastapi.io'],
    explorerUrl: 'https://moonbeam.moonscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1284',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Glimmer', symbol: 'GLMR', decimals: 18 },
  },
  [CHAIN_IDS.MOONRIVER]: {
    chainId: CHAIN_IDS.MOONRIVER,
    chainName: 'MoonRiver',
    shortName: 'moonriver',
    rpcUrl: [
      'https://rpc.api.moonriver.moonbeam.network',
      'https://moonriver.public.blastapi.io',
    ],
    explorerUrl: 'https://moonriver.moonscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1285',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Moonriver', symbol: 'MOVR', decimals: 18 },
  },
  [CHAIN_IDS.CRONOS_MAINNET]: {
    chainId: CHAIN_IDS.CRONOS_MAINNET,
    chainName: 'Cronos Mainnet',
    shortName: 'cronos',
    rpcUrl: ['https://cronos-evm-rpc.publicnode.com'],
    explorerUrl: 'https://cronoscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=25',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Cronos', symbol: 'CRO', decimals: 18 },
  },
  [CHAIN_IDS.KAVA_MAINNET]: {
    chainId: CHAIN_IDS.KAVA_MAINNET,
    chainName: 'Kava Mainnet',
    shortName: 'kava',
    rpcUrl: ['https://rpc.ankr.com/kava_evm'],
    explorerUrl: 'https://kavascan.com',
    apiUrl: 'https://api.verify.mintscan.io/evm/api/0x8ae',
    apiType: ApiType.OTHER,
    nativeCurrency: { name: 'Kava', symbol: 'KAVA', decimals: 18 },
  },
  [CHAIN_IDS.KROMA]: {
    chainId: CHAIN_IDS.KROMA,
    chainName: 'Kroma',
    shortName: 'kroma',
    rpcUrl: ['https://1rpc.io/kroma'],
    // explorerUrl: 'https://kromascan.com',
    explorerUrl: 'https://kroscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=255',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.AURORA_MAINNET]: {
    chainId: CHAIN_IDS.AURORA_MAINNET,
    chainName: 'Aurora Mainnet',
    shortName: 'aurora',
    rpcUrl: ['https://mainnet.aurora.dev', 'https://aurora.drpc.org'],
    explorerUrl: 'https://explorer.mainnet.aurora.dev',
    apiUrl: 'https://explorer.mainnet.aurora.dev/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.MINT]: {
    chainId: CHAIN_IDS.MINT,
    chainName: 'Mint Mainnet',
    shortName: 'mint',
    rpcUrl: [
      'https://rpc.mintchain.io',
      'https://global.rpc.mintchain.io',
      'https://asia.rpc.mintchain.io',
    ],
    explorerUrl: 'https://explorer.mintchain.io',
    apiUrl: 'https://explorer.mintchain.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.ARTHERA]: {
    chainId: CHAIN_IDS.ARTHERA,
    chainName: 'Arthera',
    shortName: 'arthera',
    rpcUrl: ['https://rpc.arthera.net'],
    explorerUrl: 'https://explorer.arthera.net/',
    apiUrl: 'https://explorer.arthera.net/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Arthera', symbol: 'AA', decimals: 18 },
  },
  [CHAIN_IDS.TAIKO_MAINNET]: {
    chainId: CHAIN_IDS.TAIKO_MAINNET,
    chainName: 'Taiko Mainnet',
    shortName: 'taiko',
    rpcUrl: [
      'https://rpc.mainnet.taiko.xyz',
      'https://taiko-rpc.publicnode.com',
    ],
    explorerUrl: 'https://taikoscan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=167000',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.FIRE_MAINNET]: {
    chainId: CHAIN_IDS.FIRE_MAINNET,
    chainName: '5ire Mainnet',
    shortName: '5ire',
    rpcUrl: ['https://rpc.5ire.network'],
    explorerUrl: 'https://5irescan.io',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: {
      name: '5ire Token',
      symbol: '5ire',
      decimals: 18,
    },
  },
  [CHAIN_IDS.MORPH]: {
    chainId: CHAIN_IDS.MORPH,
    chainName: 'Morph Mainnet',
    shortName: 'morph',
    rpcUrl: ['https://rpc-quicknode.morphl2.io'],
    explorerUrl: 'https://explorer.morphl2.io',
    apiUrl: 'https://explorer.morphl2.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'Ether', symbol: 'ETH', decimals: 18 },
  },
  [CHAIN_IDS.MERLIN_MAINNET]: {
    chainId: CHAIN_IDS.MERLIN_MAINNET,
    chainName: 'Merlin Mainnet',
    shortName: 'merlin',
    rpcUrl: ['https://rpc.merlinchain.io'],
    explorerUrl: 'https://scan.merlinchain.io',
    apiUrl: 'https://scan.merlinchain.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: { name: 'BTC', symbol: 'BTC', decimals: 18 },
  },
  [CHAIN_IDS.BERACHAIN_MAINNET]: {
    chainId: CHAIN_IDS.BERACHAIN_MAINNET,
    chainName: 'Bera Chain',
    shortName: 'bera',
    rpcUrl: [
      'https://berachain.blockpi.network/v1/rpc/public',
      'https://bartio.rpc.berachain.com',
      'https://bera-testnet.nodeinfra.com',
    ],
    explorerUrl: 'https://berascan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=80094',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'BERA Token',
      symbol: 'BERA',
      decimals: 18,
    },
  },
  [CHAIN_IDS.SONIC_MAINNET]: {
    chainId: CHAIN_IDS.SONIC_MAINNET,
    chainName: 'Sonic',
    shortName: 'sonic',
    rpcUrl: [
      `https://sonic-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://sonic.drpc.org',
      'https://rpc.ankr.com/sonic_mainnet',
      'https://rpc.soniclabs.com',
    ],
    explorerUrl: 'https://sonicscan.org',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=146',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'Sonic Token',
      symbol: 'S',
      decimals: 18,
    },
  },
  [CHAIN_IDS.SONEIUM_MAINNET]: {
    chainId: CHAIN_IDS.SONEIUM_MAINNET,
    chainName: 'Soneium',
    shortName: 'soneium',
    rpcUrl: [
      `https://soneium-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
    ],
    explorerUrl: 'https://soneium.blockscout.com',
    apiUrl: 'https://soneium.blockscout.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.ABSTRACT_MAINNET]: {
    chainId: CHAIN_IDS.ABSTRACT_MAINNET,
    chainName: 'Abstract',
    shortName: getZkChainConfig(CHAIN_IDS.ABSTRACT_MAINNET).shortName,
    rpcUrl: [
      `https://abstract-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://api.mainnet.abs.xyz',
      'https://abstract.drpc.org',
    ],
    explorerUrl: 'https://abscan.org',
    // apiType: ApiType.NONE,
    // apiType: ApiType.ETHERSCAN_V2,
    // apiUrl: "https://api.etherscan.io/v2/api?chainid=2741",
    apiType: ApiType.ETHERSCAN_V1,
    apiUrl: 'https://api.abscan.org/api',
    apiKeyName: NODE_ENV_VAR_NAMES.ABSTRACT_API_KEY,
    verifyKeyName: getZkChainConfig(CHAIN_IDS.ABSTRACT_MAINNET).shortNameZk,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.ABSTRACT_TESTNET]: {
    chainId: CHAIN_IDS.ABSTRACT_TESTNET,
    chainName: 'Abstract Testnet',
    shortName: getZkChainConfig(CHAIN_IDS.ABSTRACT_TESTNET).shortName,
    rpcUrl: ['https://api.testnet.abs.xyz'],
    explorerUrl: 'https://explorer.testnet.abs.xyz',
    apiUrl: 'https://api-sepolia.abscan.org/api',
    // apiUrl: "https://api.etherscan.io/v2/api?chainid=11124",
    apiType: ApiType.ETHERSCAN_V1,
    apiKeyName: NODE_ENV_VAR_NAMES.ABSTRACT_API_KEY,
    // verifyKeyName: getZkChainConfig(CHAIN_IDS.ABSTRACT_TESTNET).shortNameZk,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.INK]: {
    chainId: CHAIN_IDS.INK,
    chainName: 'Ink',
    shortName: 'ink',
    rpcUrl: ['https://rpc-gel.inkonchain.com', 'https://ink.drpc.org'],
    explorerUrl: 'https://explorer.inkonchain.com',
    apiUrl: 'https://explorer.inkonchain.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.LENS]: {
    chainId: CHAIN_IDS.LENS,
    chainName: 'Lens',
    shortName: getZkChainConfig(CHAIN_IDS.LENS).shortName,
    rpcUrl: [
      `https://lens-mainnet.g.alchemy.com/v2/<${NODE_ENV_VAR_NAMES.ALCHEMY_API_KEY}>`,
      'https://rpc.lens.xyz',
      'https://api.lens.matterhosted.dev',
    ],
    explorerUrl: 'https://explorer.lens.xyz',
    apiType: ApiType.NONE,
    // apiUrl: "https://verify.lens.xyz/contract_verification",
    // apiUrl: "https://api-explorer-verify.lens.matterhosted.dev/contract_verification",
    nativeCurrency: {
      name: 'Gho',
      symbol: 'GHO',
      decimals: 18,
    },
  },
  [CHAIN_IDS.LENS_TESTNET]: {
    chainId: CHAIN_IDS.LENS_TESTNET,
    chainName: 'Lens Testnet',
    shortName: getZkChainConfig(CHAIN_IDS.LENS_TESTNET).shortName,
    rpcUrl: ['https://rpc.testnet.lens.xyz'],
    explorerUrl: 'https://explorer.testnet.lens.xyz',
    apiType: ApiType.NONE,
    nativeCurrency: {
      name: 'Gho',
      symbol: 'GHO',
      decimals: 18,
    },
  },
  [CHAIN_IDS.SEI_EVM_MAINNET]: {
    chainId: CHAIN_IDS.SEI_EVM_MAINNET,
    chainName: 'Sei Evm',
    shortName: 'sei',
    rpcUrl: ['https://evm-rpc.sei-apis.com'],
    // explorerUrl: 'https://seitrace.com/?chain=pacific-1',
    explorerUrl: 'https://seitrace.com',
    apiUrl: 'https://seitrace.com/pacific-1/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'Sei',
      symbol: 'SEI',
      decimals: 18,
    },
  },
  [CHAIN_IDS.KAIA]: {
    chainId: CHAIN_IDS.KAIA,
    chainName: 'Kaia',
    shortName: 'kaia',
    rpcUrl: ['https://public-en.node.kaia.io/'],
    explorerUrl: 'https://kaiascan.io',
    apiUrl: 'https://mainnet-api.kaiascan.io/hardhat-verify',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'Kaia',
      symbol: 'KAIA',
      decimals: 18,
    },
  },
  [CHAIN_IDS.AI_LAYER]: {
    chainId: CHAIN_IDS.AI_LAYER,
    chainName: 'Ai Layer',
    shortName: 'ailayer',
    rpcUrl: ['https://mainnet-rpc.ailayer.xyz'],
    explorerUrl: 'https://mainnet-explorer.ailayer.xyz',
    apiUrl: 'https://mainnet-explorer.ailayer.xyz/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'BTC',
      symbol: 'BTC',
      decimals: 18,
    },
  },
  [CHAIN_IDS.B2SQUARE_NETWORK]: {
    chainId: CHAIN_IDS.B2SQUARE_NETWORK,
    chainName: 'B2Square Network',
    shortName: 'b2square',
    rpcUrl: [
      'https://mainnet.b2-rpc.com',
      'https://rpc.bsquared.network',
      'https://b2-mainnet.alt.technology',
      'https://b2-mainnet-public.s.chainbase.com',
      'https://rpc.ankr.com/b2',
    ],
    explorerUrl: 'https://explorer.bsquared.network',
    apiUrl: 'https://explorer.bsquared.network/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'BTC',
      symbol: 'BTC',
      decimals: 18,
    },
  },
  [CHAIN_IDS.BITLAYER]: {
    chainId: CHAIN_IDS.BITLAYER,
    chainName: 'Bitlayer',
    shortName: 'bitlayer',
    rpcUrl: ['https://rpc.bitlayer-rpc.com'],
    explorerUrl: 'https://www.btrscan.com',
    apiUrl: 'https://api.btrscan.com/scan/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'BTC',
      symbol: 'BTC',
      decimals: 18,
    },
  },
  [CHAIN_IDS.BOUNCE_BIT]: {
    chainId: CHAIN_IDS.BOUNCE_BIT,
    chainName: 'BounceBit',
    shortName: 'bouncebit',
    rpcUrl: ['https://fullnode-mainnet.bouncebitapi.com'],
    explorerUrl: 'https://bbscan.io',
    apiUrl: 'https://sourcify-api.bbscan.io',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: {
      name: 'BounceBit',
      symbol: 'BB',
      decimals: 18,
    },
  },
  [CHAIN_IDS.BI_FROST]: {
    chainId: CHAIN_IDS.BI_FROST,
    chainName: 'BiFrost',
    shortName: 'bifrost',
    rpcUrl: [
      'https://bifrost-mainnet.g.allthatnode.com/archive/evm',
      'https://public-01.mainnet.bifrostnetwork.com/rpc',
      'https://public-02.mainnet.bifrostnetwork.com/rpc',
    ],
    explorerUrl: 'https://explorer.mainnet.bifrostnetwork.com',
    apiUrl: 'https://explorer.mainnet.bifrostnetwork.com/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'BiFrostCoin',
      symbol: 'BFC',
      decimals: 18,
    },
  },
  [CHAIN_IDS.FILECOIN_MAINNET]: {
    chainId: CHAIN_IDS.FILECOIN_MAINNET,
    chainName: 'Filecoin Mainnet',
    shortName: 'filecoin',
    rpcUrl: [
      'https://api.node.glif.io',
      'https://filfox.info/rpc/v1',
      'https://filecoin.drpc.org',
      'https://filecoin-mainnet.chainstacklabs.com/rpc/v1',
      'https://rpc.ankr.com/filecoin',
    ],
    explorerUrl: 'https://filecoin.blockscout.com',
    apiUrl: 'https://filecoin.blockscout.com/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'Filecoin',
      symbol: 'FIL',
      decimals: 18,
    },
  },
  [CHAIN_IDS.FLARE]: {
    chainId: CHAIN_IDS.FLARE,
    chainName: 'Flare',
    shortName: 'flare',
    rpcUrl: [
      'https://flare-api.flare.network/ext/C/rpc',
      'https://flare.rpc.thirdweb.com',
      'https://flare-bundler.etherspot.io',
      'https://rpc.ankr.com/flare',
      'https://01-gravelines-003-01.rpc.tatum.io/ext/bc/C/rpc',
      'https://01-vinthill-003-02.rpc.tatum.io/ext/bc/C/rpc',
      'https://rpc.au.cc/flare',
      'https://flare.enosys.global/ext/C/rpc',
      'https://flare.solidifi.app/ext/C/rpc',
    ],
    explorerUrl: 'https://flare-explorer.flare.network',
    apiUrl: 'https://flare-explorer.flare.network/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'Flare',
      symbol: 'FLR',
      decimals: 18,
    },
  },
  [CHAIN_IDS.HYPER_EVM]: {
    chainId: CHAIN_IDS.HYPER_EVM,
    chainName: 'Hyper EVM',
    shortName: 'hyperevm',
    rpcUrl: [
      'https://rpc.hyperliquid.xyz/evm',
      'https://hyperliquid-json-rpc.stakely.io',
    ],
    explorerUrl: 'https://hyperscan.gas.zip',
    apiUrl: 'https://hyperscan.gas.zip/api',
    apiType: ApiType.OTHER,
    // explorerUrl: 'https://purrsec.com',
    // apiUrl: 'https://sourcify.parsec.finance',
    // apiType: ApiType.SOURCIFY,
    nativeCurrency: {
      name: 'Hyper',
      symbol: 'HYPE',
      decimals: 18,
    },
  },
  [CHAIN_IDS.HEMI]: {
    chainId: CHAIN_IDS.HEMI,
    chainName: 'Hemi',
    shortName: 'hemi',
    rpcUrl: ['https://rpc.hemi.network/rpc'],
    explorerUrl: 'https://explorer.hemi.xyz',
    apiUrl: 'https://explorer.hemi.xyz/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.IOTA_EVM]: {
    chainId: CHAIN_IDS.IOTA_EVM,
    chainName: 'IOTA EVM',
    shortName: 'iota',
    rpcUrl: ['https://iota-mainnet-evm.public.blastapi.io'],
    explorerUrl: 'https://explorer.evm.iota.org',
    apiUrl: 'https://explorer.evm.iota.org/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'Iota',
      symbol: 'IOTA',
      decimals: 18,
    },
  },
  [CHAIN_IDS.OPBNB_MAINNET]: {
    chainId: CHAIN_IDS.OPBNB_MAINNET,
    chainName: 'OPBNB',
    shortName: 'opbnb',
    rpcUrl: [
      'https://opbnb-mainnet-rpc.bnbchain.org',
      'https://opbnb-rpc.publicnode.com',
    ],
    explorerUrl: 'https://opbnb.bscscan.com',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=204',
    apiType: ApiType.ETHERSCAN_V2,
    nativeCurrency: {
      name: 'BNB',
      symbol: 'BNB',
      decimals: 18,
    },
  },
  [CHAIN_IDS.PULSE_CHAIN]: {
    chainId: CHAIN_IDS.PULSE_CHAIN,
    chainName: 'Pulse Chain',
    shortName: 'pulse',
    rpcUrl: [
      'https://rpc.pulsechain.com',
      'https://pulsechain-rpc.publicnode.com',
    ],
    explorerUrl: 'https://scan.pulsechainfoundation.org/#',
    apiUrl: 'https://api.scan.pulsechain.com/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'Plus',
      symbol: 'PLS',
      decimals: 18,
    },
  },
  [CHAIN_IDS.RONIN]: {
    chainId: CHAIN_IDS.RONIN,
    chainName: 'Ronin',
    shortName: 'ronin',
    rpcUrl: ['https://api.roninchain.com/rpc'],
    explorerUrl: 'https://app.roninchain.com',
    apiUrl: 'https://sourcify.roninchain.com/server',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: {
      name: 'Ronin',
      symbol: 'RON',
      decimals: 18,
    },
  },
  [CHAIN_IDS.STORY]: {
    chainId: CHAIN_IDS.STORY,
    chainName: 'Story',
    shortName: 'story',
    rpcUrl: ['https://mainnet.storyrpc.io'],
    explorerUrl: 'https://www.storyscan.io',
    apiUrl: 'https://www.storyscan.io/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'IP',
      symbol: 'IP',
      decimals: 18,
    },
  },
  [CHAIN_IDS.TRON_MAINNET]: {
    chainId: CHAIN_IDS.TRON_MAINNET,
    chainName: 'Tron',
    shortName: 'tron',
    rpcUrl: [
      'https://rpc.ankr.com/tron_jsonrpc',
      'https://api.trongrid.io/jsonrpc',
    ],
    explorerUrl: 'https://tronscan.org',
    apiType: ApiType.NONE,
    nativeCurrency: {
      name: 'Tron',
      symbol: 'TRX',
      decimals: 18,
    },
  },
  [CHAIN_IDS.ZKFAIR]: {
    chainId: CHAIN_IDS.ZKFAIR,
    chainName: 'ZKFair',
    shortName: 'zkfair',
    rpcUrl: ['https://rpc.zkfair.io'],
    explorerUrl: 'https://scan.zkfair.io',
    apiUrl: 'https://scan.zkfair.io/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'USDC',
      symbol: 'USDC',
      decimals: 18,
    },
  },
  [CHAIN_IDS.ZKLINK_MAINNET]: {
    chainId: CHAIN_IDS.ZKLINK_MAINNET,
    chainName: 'ZKLink',
    shortName: 'zklink',
    rpcUrl: ['https://rpc.zklink.io'],
    explorerUrl: 'https://explorer.zklink.io',
    apiUrl: 'https://explorer.zklink.io/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'Ether',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.UNICHAIN]: {
    chainId: CHAIN_IDS.UNICHAIN,
    chainName: 'Unichian',
    shortName: 'unichain',
    rpcUrl: ['https://mainnet.unichain.org'],
    explorerUrl: 'https://uniscan.xyz',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=130',
    apiType: ApiType.ETHERSCAN_V2,
    apiKeyName: NODE_ENV_VAR_NAMES.ETHERSCAN_V2_API_KEY,
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.UNICHAIN_SEPOLIA]: {
    chainId: CHAIN_IDS.UNICHAIN_SEPOLIA,
    chainName: 'Unichian Sepolia',
    shortName: 'uniSepolia',
    rpcUrl: [
      'https://unichain-sepolia-rpc.publicnode.com',
      'https://sepolia.unichain.org',
    ],
    explorerUrl: 'https://sepolia.uniscan.xyz',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=1301',
    apiType: ApiType.ETHERSCAN_V2,
    apiKeyName: NODE_ENV_VAR_NAMES.ETHERSCAN_V2_API_KEY,
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.BAHAMUT_MAINNET]: {
    chainId: CHAIN_IDS.BAHAMUT_MAINNET,
    chainName: 'Bahamut',
    shortName: 'bahamut',
    rpcUrl: ['https://rpc.ankr.com/bahamut'],
    explorerUrl: 'https://www.ftnscan.com',
    apiUrl: 'https://www.ftnscan.com/api',
    apiType: ApiType.OTHER,
    nativeCurrency: {
      name: 'FTN',
      symbol: 'FTN',
      decimals: 18,
    },
  },
  [CHAIN_IDS.IMMUTABLE_ZKEVM]: {
    chainId: CHAIN_IDS.IMMUTABLE_ZKEVM,
    chainName: 'Immutable zkEVM',
    shortName: 'immutableZk',
    rpcUrl: ['https://rpc.immutable.com', 'https://immutable-zkevm.drpc.org'],
    explorerUrl: 'https://explorer.immutable.com',
    apiUrl: 'https://explorer.immutable.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'IMX ',
      symbol: 'IMX ',
      decimals: 18,
    },
  },
  [CHAIN_IDS.SWELLCHAIN]: {
    chainId: CHAIN_IDS.SWELLCHAIN,
    chainName: 'Swell Chain',
    shortName: 'swell',
    rpcUrl: [
      'https://rpc.ankr.com/swell',
      'https://swell-mainnet.alt.technology',
    ],
    explorerUrl: 'https://explorer.swellnetwork.io',
    apiUrl: 'https://explorer.swellnetwork.io/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.APE_CHAIN]: {
    chainId: CHAIN_IDS.APE_CHAIN,
    chainName: 'Ape Chain',
    shortName: 'ape',
    rpcUrl: ['https://rpc.apechain.com', 'https://apechain.drpc.org'],
    explorerUrl: 'https://apescan.io',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=33139',
    apiType: ApiType.ETHERSCAN_V2,
    apiKeyName: NODE_ENV_VAR_NAMES.ETHERSCAN_V2_API_KEY,
    nativeCurrency: {
      name: 'Ape',
      symbol: 'APE',
      decimals: 18,
    },
  },
  [CHAIN_IDS.WORLD_CHAIN]: {
    chainId: CHAIN_IDS.WORLD_CHAIN,
    chainName: 'World Chain',
    shortName: 'world',
    rpcUrl: [
      'https://480.rpc.thirdweb.com',
      'https://worldchain-mainnet.g.alchemy.com/public',
      'https://node.histori.xyz/worldchain-mainnet/8ry9f6t9dct1se2hlagxnd9n2a',
      'https://sparkling-autumn-dinghy.worldchain-mainnet.quiknode.pro',
      'https://worldchain.drpc.org',
    ],
    explorerUrl: 'https://worldscan.org',
    apiUrl: 'https://api.etherscan.io/v2/api?chainid=480',
    apiType: ApiType.ETHERSCAN_V2,
    apiKeyName: NODE_ENV_VAR_NAMES.ETHERSCAN_V2_API_KEY,
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.SUPER_POSITION]: {
    chainId: CHAIN_IDS.SUPER_POSITION,
    chainName: 'SuperPositon',
    shortName: 'superpos',
    rpcUrl: ['https://rpc.superposition.so'],
    explorerUrl: 'https://explorer.superposition.so',
    apiUrl: 'https://explorer.superposition.so/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.GOAT]: {
    chainId: CHAIN_IDS.GOAT,
    chainName: 'Goat',
    shortName: 'goat',
    rpcUrl: ['https://rpc.goat.network', 'https://goat-mainnet-alpha.drpc.org'],
    explorerUrl: 'https://explorer.goat.network',
    apiUrl: 'https://explorer.goat.network/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'Bitcoin',
      symbol: 'BTC',
      decimals: 18,
    },
  },
  [CHAIN_IDS.MONAD_TESTNET]: {
    chainId: CHAIN_IDS.MONAD_TESTNET,
    chainName: 'Monad Testnet',
    shortName: 'monadTestnet',
    rpcUrl: ['https://testnet-rpc.monad.xyz'],
    explorerUrl: 'https://testnet.monadexplorer.com',
    apiUrl: 'https://sourcify-api-monad.blockvision.org',
    apiType: ApiType.SOURCIFY,
    nativeCurrency: {
      name: 'MON',
      symbol: 'MON',
      decimals: 18,
    },
  },
  [CHAIN_IDS.CRONOS_ZKEVM_MAINNET]: {
    chainId: CHAIN_IDS.CRONOS_ZKEVM_MAINNET,
    chainName: 'Cronos ZKEVM',
    shortName: getZkChainConfig(CHAIN_IDS.CRONOS_ZKEVM_MAINNET).shortName,
    rpcUrl: [
      'https://mainnet.zkevm.cronos.org',
      'https://cronos-zkevm.drpc.org',
    ],
    explorerUrl: 'https://explorer.zkevm.cronos.org',
    apiType: ApiType.NONE,
    nativeCurrency: {
      name: 'zkCRO',
      symbol: 'zkCRO',
      decimals: 18,
    },
  },
  [CHAIN_IDS.SUPERSEED]: {
    chainId: CHAIN_IDS.SUPERSEED,
    chainName: 'Superseed',
    shortName: 'superseed',
    rpcUrl: ['https://superseed.drpc.org', 'https://mainnet.superseed.xyz'],
    explorerUrl: 'https://explorer.superseed.xyz',
    apiType: ApiType.BLOCKSCOUT,
    apiUrl: 'https://explorer.superseed.xyz/api',
    nativeCurrency: {
      name: 'Eth',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.LISK_MAINNET]: {
    chainId: CHAIN_IDS.LISK_MAINNET,
    chainName: 'Lisk Mainnet',
    shortName: 'lisk',
    rpcUrl: ['https://lisk.drpc.org', 'https://rpc.api.lisk.com'],
    explorerUrl: 'https://blockscout.lisk.com',
    apiType: ApiType.BLOCKSCOUT,
    apiUrl: 'https://blockscout.lisk.com/api',
    nativeCurrency: {
      name: 'Eth',
      symbol: 'ETH',
      decimals: 18,
    },
  },
  [CHAIN_IDS.METAL_L2]: {
    chainId: CHAIN_IDS.METAL_L2,
    chainName: 'Metal L2',
    shortName: 'metal',
    rpcUrl: [
      'https://rpc.metall2.com',
      'https://metall2.drpc.org',
      'https://l2-metal-mainnet-0.t.conduit.xyz',
    ],
    explorerUrl: 'https://explorer.metall2.com',
    apiUrl: 'https://explorer.metall2.com/api',
    apiType: ApiType.BLOCKSCOUT,
    nativeCurrency: {
      name: 'Eth',
      symbol: 'ETH',
      decimals: 18,
    },
  },
}
