/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../../common";
import type {
  ArgumentsDecoder,
  ArgumentsDecoderInterface,
} from "../../../../contracts/Test/AggregationRouterV5.sol/ArgumentsDecoder";

const _abi = [
  {
    inputs: [],
    name: "IncorrectDataLength",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60808060405234601757603a9081601d823930815050f35b600080fdfe600080fdfea264697066735822122056185bf15963ef4e61448185fa0b4f0b547fa17b6f813a3577e10dd4979dabf564736f6c63430008130033";

type ArgumentsDecoderConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ArgumentsDecoderConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ArgumentsDecoder__factory extends ContractFactory {
  constructor(...args: ArgumentsDecoderConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ArgumentsDecoder> {
    return super.deploy(overrides || {}) as Promise<ArgumentsDecoder>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ArgumentsDecoder {
    return super.attach(address) as ArgumentsDecoder;
  }
  override connect(signer: Signer): ArgumentsDecoder__factory {
    return super.connect(signer) as ArgumentsDecoder__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ArgumentsDecoderInterface {
    return new utils.Interface(_abi) as ArgumentsDecoderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ArgumentsDecoder {
    return new Contract(address, _abi, signerOrProvider) as ArgumentsDecoder;
  }
}
